### ISSUE TITLE
FeatureRequest: Can diun if it has an update target container function use docker labels?

### ISSUE THREAD

**Issue by Leopere** [crazy-max/diun#1]
With a number of other things like [Watchtower](https://github.com/containrrr/watchtower) and [Ouroboros](https://github.com/pyouroboros/ouroboros) you can establish [container labels](https://docs.docker.com/engine/reference/commandline/run/) these labels can present triggers to other docker controlling and monitoring systems.  

The thing I would love to see is for Diun to look for labels and just automatically detect the container's source and run checks against the upstream repository.

One such example is in the [ouroboros documentation](https://github.com/pyouroboros/ouroboros/wiki/Usage#label-enable) where the label determines to the Ouroboros appliance if the container should be handled by Ouroboros.

In this case, you could have a few labels I'm sure.

**Comment by crazy-max** [comment]
Hi @Leopere,

Perhaps I misunderstood your request, but I would like to point out that unlike other tools like WatchTower, Diun is not intended to update containers but only to send notifications when an image is updated on a registry.

On the other hand, I have planned in my [TODO list](https://github.com/crazy-max/diun#todo) to check images running via the Docker daemon. We could potentially use labels to filter those we want to analyze.

**Comment by Leopere** [comment]
The misunderstanding was mine I skimmed the documentation after seeing your
post on /r/docker and though I saw mentions of an update function. I love
the project thanks for the contribution to the internet.

**Comment by Leopere** [comment]
Closed in lieu of the creation of #3
