### ISSUE TITLE
Feature: Discord support

### ISSUE THREAD

**Issue by jbpratt78** [crazy-max/diun#110]
Neat project! Notifications via Discord would be great.

https://github.com/bwmarrin/discordgo
https://github.com/andersfylling/disgord

or simply through a [webhook](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks) as other providers are implemented

**Comment by crazy-max** [comment]
Hi @jbpratt78,

I think @j0nnymoe made it work on Discord with the [Webhook notifier](https://crazy-max.github.io/diun/notif/webhook/).

**Comment by jbpratt78** [comment]
Feel free to close this :+1:

**Comment by crazy-max** [comment]
@jbpratt78 If you have a recipe for Discord, feel free to share it
