### ISSUE TITLE
[Feature request] Support Pushover message priority

### ISSUE THREAD

**Issue by JaneDilbert** [crazy-max/diun#1108]
### Description

Hi,

I liked the project, is simple to implement and very effective. Exactly what I was looking for. And I was very happy to see it natively supports Pushover integration. 

Since the Pushover API integration is already in place, would it be possible to add support for [message priority](https://pushover.net/api#priority) through an additional environment parameter?

Otherwise, the only way to configure notification rules is going through mail.

Thanks!

**Comment by crazy-max** [comment]
Already available using the `priority` attribute: https://crazymax.dev/diun/notif/pushover/#configuration
