### ISSUE TITLE
Can't send mail notification through gmail

### ISSUE THREAD

**Issue by SR-G** [crazy-max/diun#1175]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hey.
Trying to activate the gmail notification, and nothing is working, despite many tries (port 587 versus 25, ssl true/false, insecureSkipVerify true/false, ...).
Is there a working configuration somewher ?? (the one found in another (closed) bug with port "25" is NOT working).

Right now my configuration is : 

```
notif:
  mail:
    host: smtp.gmail.com
    port: 587
    ssl: true
    username: webmaster@domain.com
    password: XXXXXXXXXXXXXXXXXXX
    insecureSkipVerify: false
    from: webmaster@domain.com
    to:
      - me@gmail.com
```

which should be working (i'm using the exact same values with many other services, for example a working correspindg .msmtprc file is  : 

```
account        gmail
auth           plain
host           smtp.gmail.com
port           587
from           webmaster@domain.com
user           webmaster@domain.com
password       XXXXXXXXXXXXXXXX
tls_nocertcheck
```

### Expected behaviour

No errors when GMAIL notifications are sent

### Actual behaviour

DIUN is not able to send GMAIL notifications

### Steps to reproduce

Configure diun with GMAIL settings

### Diun version

4.28.0

### Docker info

```text
This is not "docker related"
```

### Logs

Errors are like (depending of what is true/false) : 

```text
Sun, 19 May 2024 12:58:22 CEST ERR Mail notification failed error="dial tcp 66.102.1.108:25: i/o timeout" image=ghcr.io/funkeyflo/ps5-mqtt/amd64:1.2.1

Sun, 19 May 2024 12:55:39 CEST ERR Mail notification failed error="gomail: could not send email 1: 421 4.3.0 Temporary System Problem. Try again later (10). For more information,\n4.3.0 go to\n4.3.0  https://support.google.com/a/answer/3221692 ffacd0b85a97d-3502b8a76e6sm26424236f8f.62 - gsmtp" image=ghcr.io/funkeyflo/ps5-mqtt/amd64:1.3.1

Sun, 19 May 2024 12:52:18 CEST ERR Mail notification failed error="tls: first record does not look like a TLS handshake" image=ghcr.io/home-assistant/home-assistant:2024.5.4

etc.
```

**Comment by crazy-max** [comment]
Looking at `421 4.3.0 Temporary System Problem` and https://support.google.com/a/answer/3221692 from your logs, the error code `421` says `Service isn't available, try again later`. Maybe there is an intermittent network issue on your host.
