### ISSUE TITLE
Avoid to skip notification on first check

### ISSUE THREAD

**Issue by fam4r** [crazy-max/diun#1197]
### Description

I would like to get the notification on first check. At the moment DIUN skips the notification even if it finds new images for existing containers on first run.

Please consider letting the users disable this behavior.

```
diun  | Tue, 18 Jun 2024 18:40:17 CEST INF New image found image=lscr.io/linuxserver/mariadb:latest provider=docker
diun  | Tue, 18 Jun 2024 18:40:17 CEST DBG Manifest saved to database image=lscr.io/linuxserver/mariadb:latest provider=docker
diun  | Tue, 18 Jun 2024 18:40:17 CEST DBG Skipping notification (first check) image=lscr.io/linuxserver/mariadb:latest provider=docker
```

**Comment by NJYZ-96** [comment]
Yes, I would recommend this too to avoid skipping notifications on the first check; I thought it was a problem with my configuration because I didn't get notifications the first time and spent an hour looking for the problem

**Comment by crazy-max** [comment]
> I would like to get the notification on first check

Same as https://github.com/crazy-max/diun/pull/1267#issuecomment-2543316933

You need to set [`firstCheckNotif` to `true`](https://crazymax.dev/diun/config/watch/#firstchecknotif)
