### ISSUE TITLE
Command to list all the images from diun.db that are being checked

### ISSUE THREAD

**Issue by Vorsku** [crazy-max/diun#138]
Hi,

Firstly, thank you for the project - it's my most useful container! 👍

I was wondering if it was possible to implement the ability to list all the images that are present in diun.db - possibly by running a command on the running container like:

```
docker exec diuncontainer diun --list
```

Alternatively, I tried copying the diun.db file out and opening it in a SQLite browser but it wanted a passphrase to unlock the database - is this passphrase something that can be configured, or can I see where it is?

Thanks!

**Comment by crazy-max** [comment]
Hi @Vorsku,

> Alternatively, I tried copying the diun.db file out and opening it in a SQLite browser but it wanted a passphrase.

This is not a SQLite database. Diun currently uses the embedded key/value database [bbolt](https://github.com/etcd-io/bbolt). You can use [boltBrowser](https://github.com/ShoshinNikita/boltBrowser) which is a GUI web-based explorer and editor or [this CLI browser](https://github.com/br0xen/boltbrowser).

**Comment by Vorsku** [comment]
Doh! Thanks, I'll look at that!

It would still be cool to be able to run a command like ```diun --list``` to view all the images polled :)

**Comment by crazy-max** [comment]
@Vorsku 

> It would still be cool to be able to run a command like `diun --list` to view all the images polled :)

Yep LGTM

**Comment by crazy-max** [comment]
@Vorsku @richardneish Available in latest release. Let me know if it looks good to you.
