### ISSUE TITLE
Support using m.message instead of m.notice for Matrix notifications

### ISSUE THREAD

**Issue by PopeRigby** [crazy-max/diun#143]
This just changes the way the notifications are handled in clients. `m.notice`, which it's set to currently, is better for a bot that sits in a room with more than one person and gives updates in the background. `m.message` is better suited to my situation, which is just me and the bot sitting in the room, and me wanting to get notified of every Docker update.

**Comment by crazy-max** [comment]
@PopeRigby [`msgType` option](https://crazy-max.github.io/diun/notif/matrix/#configuration) has been added.
