### ISSUE TITLE
Email notifications not working

### ISSUE THREAD

**Issue by ludipq** [crazy-max/diun#149]
Added configuration for SMTP as per the documentation. When running `diun --test-notif` this is the output:

> Sat, 15 Aug 2020 18:40:57 CEST INF Starting Diun version=4.4.0
> Sat, 15 Aug 2020 18:40:57 CEST INF Configuration loaded from file: /etc/diun/diun.yaml
> Sat, 15 Aug 2020 18:40:57 CEST INF Configuration loaded from 5 environment variable(s)
> **Sat, 15 Aug 2020 18:41:07 CEST FTL Cannot initialize Diun error=timeout**

Using the same SMTP settings on [SMTPer](https://www.smtper.net) works fine.

**Comment by crazy-max** [comment]
@ludipq Please create a proper [bug report](https://github.com/crazy-max/diun/issues/new?template=bug_report.md). Thanks.
