### ISSUE TITLE
Too many requests to registry

### ISSUE THREAD

**Issue by dynek** [crazy-max/diun#168]
### Steps to reproduce this issue

1. Define label diun.watch_repo to true on 12 images
2. Watch logs

### Expected behaviour

> I'd expect Diun to report if a newer image came out (basically if a new tag made it to the docker hub)

### Actual behaviour

> Log is _flooded_ with "Cannot create image closer: too many requests to registry"

## Configuration

* Diun version : 4.5.0
* Platform (windows/linux) : Li ux
* System info (type `uname -a`) : Linux pve 5.4.24-1-pve #1 SMP PVE 5.4.24-1 (Mon, 09 Mar 2020 12:59:46 +0100) x86_64 GNU/Linux

**Comment by dynek** [comment]
I'm not quite sure how to use Diun, as I thought an initial docker hub _scan_ would be down to gather tags and then when a new one is created, then a notification is sent.

How can I watch the docker hub for new tags for 12 images without hitting "too many requests to registry"?

Thank you

**Comment by crazy-max** [comment]
Hi @dynek,

> How can I watch the docker hub for new tags for 12 images without hitting "too many requests to registry"?

You should first authenticate against DockerHub through the [`regopts` settings](https://crazymax.dev/diun/config/regopts/). If it's not enough, tweak the schedule with something like `0 */6 * * *` (every 6 hours).

I will add a section in the FAQ about that.

**Comment by dynek** [comment]
Much better @crazy-max, thanks a bunch!
