### ISSUE TITLE
Cannot load configuration error="Key: 'Config.RegOpts[2].Selector' Error:Field validation for 'Selector' failed on the 'oneof' tag"

### ISSUE THREAD

**Issue by TomMir** [crazy-max/diun#174]
## Behaviour

1. File diun.yml in /etc/diun:
db:
  path: diun.db

watch:
  workers: 20
  schedule: "0 */6 * * *"

regopts:
  - name: "myregistry"
    username: fii
    password: bor
    timeout: 5s
  - name: "docker.io/crazymax"
    selector: image
    username: fii
    password: bor
  - name: "docker.io"
    selector: "gitlab/gitlab-ce"

providers:
  file:
    filename: ./config.yml

2.file config.yml in /etc/diun:
# Watch crazymax/swarm-cronjob image and assume docker.io registry and latest tag
# with registry options named 'docker.io/crazymax' (image selector).
# Only include tags matching regexp ^1\.2\..*
- name: gitlab/gitlab-ce
  watch_repo: true
  include_tags:
    - ^1\.2\..*

3.

### Expected behaviour
List of tags

> Tell me what should happen

### Actual behaviour
root@DESKTOP-JD6SGGF:/etc/diun# diun --config diun.yml
Wed, 16 Sep 2020 07:39:34 UTC INF Starting Diun version=4.5.0
Wed, 16 Sep 2020 07:39:34 UTC INF Configuration loaded from file: /etc/diun/diun.yml
Wed, 16 Sep 2020 07:39:34 UTC FTL Cannot load configuration error="Key: 'Config.RegOpts[2].Selector' Error:Field validation for 'Selector' failed on the 'oneof' tag"

> Tell me what happens instead

## Configuration

* Diun version : 
the latest
* Platform (windows/linux) :
windows 10 wsl ubuntu 20.04
* System info (type `uname -a`) : 

> Paste your configuration files here
> * docker-compose.yml
> * k8s deployment configuration
> * environment variables
> * diun config file
> * ...

### Logs

```
# paste logs here (set log-level to debug and enable log-caller)
```

[work.zip](https://github.com/crazy-max/diun/files/5230696/work.zip)

**Comment by crazy-max** [comment]
@TomMir Please format your issue correctly: https://guides.github.com/features/mastering-markdown/
