### ISSUE TITLE
Add mqtt as notification service

### ISSUE THREAD

**Issue by RezzZ** [crazy-max/diun#18]
Any chance you can add publishing to mqtt to this nice service?

**Comment by crazy-max** [comment]
@RezzZ Yes we could publish msg to topics using [yosssi/gmq](https://github.com/yosssi/gmq) for example. Feel free to open a PR.

**Comment by RezzZ** [comment]
I appreciate the offer but I really have no clue where to start. I'm still quite the newbie regarding hardcore coding :)
