### ISSUE TITLE
Please add support for Pushover notifications

### ISSUE THREAD

**Issue by derekoharrow** [crazy-max/diun#207]
Can you add support for Pushover notifications?

Pushover uses a simple REST API as described here - https://pushover.net/api

It simply requires a user token/key, an API token, and the message. 

Thanks

**Comment by TheKas** [comment]
+1

**Comment by crazy-max** [comment]
@derekoharrow #254

**Comment by derekoharrow** [comment]
Brilliant - thank you.  Works great!!
