### ISSUE TITLE
Docker rate limit

### ISSUE THREAD

**Issue by Trollwut** [crazy-max/diun#208]
Hey mates!

This might be a stupid questio, but I need some insights.

Got some Docker services running and, of course, Diun to notify me about updates.

Now I pulled and updated one (exactly one) via docker-compose, which worked as intended.

But now I wanted to update a second container and whelp, can't pull it:

    Error pulling mailcow/unbound:1.12, retrying...
    Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

So my question is:

Does using Diun affect this pull limit?

**Comment by crazy-max** [comment]
@Trollwut 

> Does using Diun affect this pull limit?

Yes this could affect the rate limit. Can you give me your compose file and diun configuration if you have one please? I would need your logs as well and the output of `docker ps -a`. Thanks.

**Comment by Trollwut** [comment]
Of course!

I guess these are the lines that are most important for it:

    DIUN_WATCH_WORKERS: 20
    DIUN_WATCH_SCHEDULE: "0 */6 * * *"
    DIUN_PROVIDERS_DOCKER: "true"
    DIUN_PROVIDERS_DOCKER_WATCHSTOPPED: "true"
    DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT: "true"

If you need any more information, please ask. I'm travelling right now, can give better details when terminal copying through SSH works at my workstation. :D 

Also this:

    $ docker ps -a | wc -l
    34

*(again, if you need detailed info, I can give it once I'm at my workstation again)*

**Comment by crazy-max** [comment]
@Trollwut Thanks for the info. Your configuration doesn't seem aggressive to me so I don't think it comes from Diun. Have you configured labels on your containers like [`diun.watch_repo=true`](https://crazymax.dev/diun/providers/docker/#docker-labels)?

**Comment by Trollwut** [comment]
Nope, haven't set any labels referencing Diun. That's why I set "WATCHBYDEFAULT" to "true", which works, as it reports new versions of my running containers.

**Comment by crazy-max** [comment]
@Trollwut With [latest release (4.8.0)](https://github.com/crazy-max/diun/releases/tag/v4.8.0), Docker Hub rate limits should now be drastically reduced by comparing the digest of the analyzed image through a `HEAD` request on the manifest that does not count towards the limit. This also improves analysis performance. More info in [the FAQ](https://crazymax.dev/diun/faq/#docker-hub-rate-limits).

**Comment by Trollwut** [comment]
Thank you very much!
