### ISSUE TITLE
Notification links for GHCR

### ISSUE THREAD

**Issue by TheSpad** [crazy-max/diun#209]
## Behaviour
Not sure if this is possible yet with how GHCR is set up, but Discord (and possibly other) notifications for images hosted on dockerhub link the image name to the dockerhub page:

![image](https://user-images.githubusercontent.com/8425502/98159779-112d9780-1ed5-11eb-9bb9-ab74e91003f3.png)

But GHCR images do not:

![image](https://user-images.githubusercontent.com/8425502/98159814-20144a00-1ed5-11eb-859e-f43fc002adba.png)

Would be a nice to have if it's possible.

**Comment by crazy-max** [comment]
@TheSpad Yes I will translate the hub link for GHCR in the notification, thanks for your input!

**Comment by crazy-max** [comment]
@TheSpad Can you test with `crazymax/diun:edge`?

**Comment by TheSpad** [comment]
I've switched diun to `edge` on my hosts and I'll let you know as soon as it picks up an update.

**Comment by TheSpad** [comment]
All working as expected:

![Screenshot_20201108-093635](https://user-images.githubusercontent.com/8425502/98461658-f3e31c80-21a5-11eb-9e39-7835288b8185.png)
