### ISSUE TITLE
Make private registries with self signed certificate possible

### ISSUE THREAD

**Issue by Docjones** [crazy-max/diun#22]
Running a private repository (eg. nexus) with https using a self signed certificate yields in 

> Cannot run job error="pinging docker registry returned: Get https://xxxx.xxxx.xxxx/v2/: x509: certificate signed by unknown authority"

additionally, it would be good to have the username/password fields as optional for registries. Plus, a method to differentiate between repositories. 

We pull images from 
* our onw repository (ssl w/o authentication)
* a suppliers repository (ssl w/o authentication)
* public repository (docker.io)

**Comment by crazy-max** [comment]
> Running a private repository (eg. nexus) with https using a self signed certificate yields in

`insecure_tls` option [is already available](https://github.com/crazy-max/diun/blob/master/doc/configuration.md#regopts).

> additionally, it would be good to have the username/password fields as optional for registries.

Authentication on the reigstry is enabled if at least the username is provided. So no auth if you leave empty username and password options.

Example:

```
regopts:
  myregistry:
    insecure_tls: true
```
