### ISSUE TITLE
Opt out of being watched?

### ISSUE THREAD

**Issue by ksurl** [crazy-max/diun#229]
if DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT is set to true and on specific containers you set diun.enable=false, does that work?

ie. I want to watch all containers except ones that are explicitly set to disabled. 

It would also be nice to have global watched tag filter instead of per container label (eg. filter all my own containers and only monitor ones maintained by 3rd parties).

**Comment by crazy-max** [comment]
@ksurl 

>  if DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT is set to true and on specific containers you set diun.enable=false, does that work?

Yes as you can see I check first if `diun.enable` is setted, otherwise I check for `watchByDefault` behavior:

https://github.com/crazy-max/diun/blob/56b87da00fba9449f05fa401b3276276cc5f1853/internal/provider/common.go#L20-L30

**Comment by ksurl** [comment]
Thanks.
