### ISSUE TITLE
Watch image not used by a container

### ISSUE THREAD

**Issue by cpwood** [crazy-max/diun#230]
Is it possible to get a notification about images that _aren't_ in use by a container?

Specifically, my use case is base images. If a base image is updated, I'd like to be triggered to update my derived image.

**Comment by crazy-max** [comment]
@cpwood You can use the file provider for that: https://crazymax.dev/diun/providers/file/

**Comment by crazy-max** [comment]
See also https://crazymax.dev/diun/user-guides/docker-file-providers/
