### ISSUE TITLE
Multiple providers and docker vs file

### ISSUE THREAD

**Issue by ksurl** [crazy-max/diun#232]
can you specify to use both docker and file providers (running containers) and a list from a file config?

and for the file provider, is it aware of the local images and checks the image digest vs the registry before actually pulling manifests?

**Comment by ksurl** [comment]
I just tested and it takes both providers. still wondering about file image checking though

**Comment by ksurl** [comment]
how should images without a latest tag be configured? I am trying to check for ghcr.io/linuxserver/baseimage-alpine so I know when it updates and to rebuild my images. they only tag based on the sha and version numbers since it's only used internally with their own ci.

**Comment by crazy-max** [comment]
@ksurl 

> Can you specify to use both docker and file providers (running containers) and a list from a file config?

Yes, I've created a user guide specially for that: #239

Please create [one issue per request/bug](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md#writing-good-bug-reports-and-feature-requests). Thanks.
