### ISSUE TITLE
Pushover notification failed error="invalid character '<'

### ISSUE THREAD

**Issue by zerocool79** [crazy-max/diun#272]
## Behaviour

Pushover notification failed for some images that are found. 
Example:

Pushover notification failed error="invalid character '<' looking for beginning of value" image=ghcr.io/linuxserver/sabnzbd:latest

* Diun version : 4.12.0
* Platform (windows/linux) : linux

**Comment by crazy-max** [comment]
@tongliang79 Can you paste your logs here please? And also a screenshot of a working notification with pushover. Thanks.

**Comment by tongliang79** [comment]
Here you go:

[debug.log](https://github.com/crazy-max/diun/files/5976858/debug.log)

Screenshot of a working pushover notification:
<img width="367" alt="Screenshot" src="https://user-images.githubusercontent.com/17445886/107866168-a531d680-6ea8-11eb-85f0-e13374a4cebf.png">

**Comment by crazy-max** [comment]
@zerocool79 I have made some changes to enhance message sanitization in #273. Can you try with `crazymax/diun:edge`?

**Comment by zerocool79** [comment]
@crazy-max , seems like the issue is still there.

[debug_20200215.log](https://github.com/crazy-max/diun/files/5980230/debug_20200215.log)

**Comment by crazy-max** [comment]
@zerocool79 Ok thanks for your feedback. Can you test with `crazymax/diun:pushover-debug` and give me your logs? Thanks.

**Comment by zerocool79** [comment]
I have used crazymax/diun:pushover-debug and it doesn't look like there is a change in version number.  But here it is regardless.
[debug_20200216.log](https://github.com/crazy-max/diun/files/5988157/debug_20200216.log)

**Comment by crazy-max** [comment]
@zerocool79 Ok thanks for the logs, First I thought the issue was about message formatting but it looks like Pushover recipient details API is the culprit here, that's why I cannot reproduce. Must be specific to your account profile on Pushover website. I have updated `crazymax/diun:pushover-debug` to print more logs and also skip the recipient details part. Can you make another test and give me your logs please? Thanks!

**Comment by crazy-max** [comment]
@zerocool79 `crazymax/diun:edge` should fix your issue. Can you confirm? Thanks!

**Comment by zerocool79** [comment]
Hi there,

Deepest apologies for the lack of response over the past few days but
family and work has kept me busy.
I do see some errors but this might not have been due to pushover.

Here is the log as attached.

**Comment by crazy-max** [comment]
@zerocool79 

> Here is the log as attached.

I don't see the log file.

**Comment by Phontana** [comment]
@crazy-max I just tested the `edge` version and the issue is still there.

**Comment by DrEsteban** [comment]
I am seeing the same here for the Prometheus image: 

```
ERR Pushover notification failed error="invalid character '<' looking for beginning of value" image=docker.io/prom/prometheus:latest
```
