### ISSUE TITLE
[Edge] Discord Notifications: links no longer rendering properly

### ISSUE THREAD

**Issue by rg9400** [crazy-max/diun#274]
## Behaviour
Previously, links used to render properly in Discord notifications, but after the messaging changes on the Edge branch, they've been having issues.

### Steps to reproduce this issue

1. Pull `crazymax/diun:edge`
2. Set up config notifier as below
``` yaml
notif:
    discord:
      webhookUrl: https://discord.com/api/webhooks/channelid/webhookid
```
3. Wait for an update to trigger the notification

### Expected behaviour

It should look like it used to in earlier versions before the messaging changes
![image](https://user-images.githubusercontent.com/39887349/107971245-db8a5700-6f77-11eb-9a78-dfb2e9aa492b.png)

### Actual behaviour

It displays like this on the latest Edge version
![image](https://user-images.githubusercontent.com/39887349/107971334-f6f56200-6f77-11eb-9c3c-842955f35651.png)

## Configuration

* Diun version : Diun v4.12.0-SNAPSHOT-c971e06
* Platform (windows/linux) : Docker running in WSL
* System info (type `uname -a`) : Linux Stormlight 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Let me know if you need further info

**Comment by crazy-max** [comment]
@rg9400 Thanks for your feedback and tests against edge tag. I will take a look.
