### ISSUE TITLE
Support of secrets in none swam environments

### ISSUE THREAD

**Issue by jzt308** [crazy-max/diun#283]
I checked the docs but couldn't find an answer. 
I would like to be able to add sensitive information (i.e. DIUN_NOTIF_ROCKETCHAT_TOKEN) as a secret instead of in the docker-compose file or the CLI.

when in  swarm mode you can use docker secrets managed by the swam for this but on  a standalone docker install this is not possible.

for example the mariadb container uses a file mount and reads the sensitive information from there or the containers from linuxserver.io use a environment var where you can read the input from a file (and lock down access to the file on the OS).

It's not necessary but maybe would be a nice addition?

**Comment by crazy-max** [comment]
@jzt308 Yes some notifiers miss this kind of behavior to use secret file as value. Matrix notifier handles this: https://crazymax.dev/diun/notif/matrix/ and we can definitely do this for the others. Keep you in touch.

**Comment by crazy-max** [comment]
@jzt308 Available, see https://crazymax.dev/diun/notif/rocketchat/
