### ISSUE TITLE
thanks and a minor feature question

### ISSUE THREAD

**Issue by mtklr** [crazy-max/diun#286]
Great project, thank you for making it!

I would love to see a "plain" log messages option without the color escape codes - logs in [ctop](https://github.com/bcicen/ctop) appear as:

```
90mSun, 28 Feb 2021 04:18:29 UTC [0m  [32mINF [0m Cron initialized with schedule 0 */12 * * *
```

Maybe ctop should support ansi codes in the logs instead? :)

Not a big deal though. Thanks again.

**Comment by crazy-max** [comment]
@mtklr A new flag has been added to disable colorized output. See https://crazymax.dev/diun/usage/cli/

**Comment by mtklr** [comment]
wow, thanks!!! :)
