### ISSUE TITLE
Synology Docker Version

### ISSUE THREAD

**Issue by Latschenharry** [crazy-max/diun#29]
Is it possible to add a lower client version, so it can also run on Synology Devices?

The Following error occurs on startup:

ERR Cannot create Docker client error="Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39" provider=docker-local

**Comment by crazy-max** [comment]
@Latschenharry You can already override the client version using `api_version` for your docker provider: https://github.com/crazy-max/diun/blob/master/doc/configuration.md#providers

**Comment by Latschenharry** [comment]
Thank you for the fast response. I only checked the docker variables.
