### ISSUE TITLE
Cannot use MQTT notification using Docker Compose Environment variables

### ISSUE THREAD

**Issue by derekoharrow** [crazy-max/diun#304]
### Steps to reproduce this issue

1. Configure DIUN MQTT notification using docker-compose environment variables instead of diun config file.
2. Start DIUN

### Expected behaviour

DIUN should start ok as usual

### Actual behaviour

DIUN fails to start and logs the errors shown below.

## Configuration

* Diun version : 3.13.0
* Platform (windows/linux) : Linux/Docker
* System info (type `uname -a`) : Linux docker 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

> Paste your configuration files here

docker-compose.yml:
```
      - "DIUN_NOTIF_MQTT_HOST=mqtt.lan"
      - "DIUN_NOTIF_MQTT_TOPIC=docker/diun"
      - "DIUN_NOTIF_MQTT_CLIENT=diun"
      - "DIUN_NOTIF_MQTT_SCHEME=mqtt"
      - "DIUN_NOTIF_MQTT_PORT=1883"

```

### Logs

```
Mon, 15 Mar 2021 15:41:07 UTC INF Starting Diun version=4.13.0
Mon, 15 Mar 2021 15:41:07 UTC FTL Cannot load configuration error="Failed to decode configuration from environment variables: Failed to decode configuration from environment variables: field not found, node: scheme"
```

**Comment by derekoharrow** [comment]
I notice that DIUN does seem to start if you exclude the line:
`      - "DIUN_NOTIF_MQTT_SCHEME=mqtt"`
     
(which the documentation says is required).

**Comment by crazy-max** [comment]
@derekoharrow Not yet deployed (https://github.com/crazy-max/diun/pull/292). The doc is based on master branch, not the latest release so in your case it should work with `crazymax/diun:edge` (master).

**Comment by crazy-max** [comment]
@derekoharrow Should be ok now.
