### ISSUE TITLE
Run without access to /var/run/docker.sock

### ISSUE THREAD

**Issue by Punkado** [crazy-max/diun#308]
Hello,
I know that for Diun to work, it need access to the docker.sock to check the image of the running container, but mounting the /var/run/docker.sock in a container is not something that i think is good idea, security wise.

For most of containers that need access to /var/run/docker.sock, like Traefik, i use [docker socket proxy](https://github.com/Tecnativa/docker-socket-proxy) to protect it. A simple DOCKER_HOST=tcp://proxy_socket:2375 in the environment do the job, but with diun it does not work. 

There is any way to accomplish that? 

Thanks

**Comment by crazy-max** [comment]
@Punkado 

> There is any way to accomplish that?

Yes you can change the endpoint: https://crazymax.dev/diun/providers/docker/#endpoint

**Comment by Punkado** [comment]
Stupid me, i didn't see it in the documentation... I am sorry for that and thanks a lot.

**Comment by travelg** [comment]
@Punkado Can you please share which minimum permissions docker socket proxy needs in order to work with Diun to check updates are available for specific container ? Thanks

**Comment by Punkado** [comment]
Hello,

Sure, here is my docker-socket-proxy composer

  dockersocket:
    image: tecnativa/docker-socket-proxy
    container_name: proxy_socket
    privileged: true
    networks:
      - dockersocket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      IMAGES: 1
      restart: unless-stopped
