### ISSUE TITLE
Question: What happens when you watch the same repo twice?

### ISSUE THREAD

**Issue by FischlerA** [crazy-max/diun#327]
I just recently discovered Diun and was planning to start using it in my Kubernetes cluster.
I have the same pod running multiple times for different use cases in my cluster (oauth2 proxy) and i am unsure what will happen if i add these labels to both of my proxies.

```
diun.enable: "true"
diun.watch_repo: "true"
```

Will i get notified for the same repository multiple times because i have multiple pods from different deployments with the same image and repository or will Diun handle this internaly and only notify me once?

I would greatly appreciate any information :)

**Comment by crazy-max** [comment]
@FischlerA 

> Will i get notified for the same repository multiple times because i have multiple pods from different deployments with the same image and repository or will Diun handle this internaly and only notify me once?

Yes you will get notified once per image.
