### ISSUE TITLE
Feature Request: Send notifications on different schedule than image checks

### ISSUE THREAD

**Issue by nearcatch** [crazy-max/diun#331]
I want diun to check for image updates every 6 hours to maximize the usage of the dockerhub rate limits, but I don't want to be notified every 6 hours if there are image changes. I just want to be notified once a day. I'd like to request a way for diun to just note the image changes internally and then send notifications just once a day (or any user defined schedule). Thoughts?

**Comment by crazy-max** [comment]
@nearcatch #10
