### ISSUE TITLE
Use multiple networks

### ISSUE THREAD

**Issue by Nico83500** [crazy-max/diun#332]
Hi,
First thank you for this app :)
I would like to use 2 differents networks : 
- An internal network to communicate between the socket proxy
- An external network to communicate to the web (to get docker hub access, updates, send notif, etc...)
Is there a way to indicate which network to use to external communications ? Or is it possible to add a feature to do that ?
Thank you !

**Comment by crazy-max** [comment]
Not sure I understand, can you give details about your use case?

**Comment by Nico83500** [comment]
I'm sorry I forgot to close because it wasn't an issue.
I would like to use something like this (socket_network is internal and diun_network is external) : 

> networks:
  socket_network:
    external: true
  diun_network:
    external: true

I thought it was necessary to indicate which network can access to Internet but it founds itself the right way so no problem.
Thank you !
