### ISSUE TITLE
--profiler flag mandatory from 4.15.0

### ISSUE THREAD

**Issue by buxm** [crazy-max/diun#340]
## Behaviour
Apparently `--profiler` flag has become mandatory from 4.15.0. However this does not appear to be so in the documentation. Also it is not clear to me what this flag is for... it looks like an option for profiling the code, hence something quite developer/troubleshooting oriented, not for day to day use.... but not quite sure.

### Steps to reproduce this issue

1.Use docker-compose.yml pasted below
2.Run command:
`docker-compose run --rm diun --log-level="debug" --log-caller --log-nocolor`

### Expected behaviour

Diun successfully checks for any updates in my running containers labeled diun.enable=true and notifies me via email of any update

### Actual behaviour

The following message appears:
```
Usage: diun

Docker image update notifier. More info: https://github.com/crazy-max/diun

diun: error: --profiler must be one of "alloc","block","cpu","heap","mem","mutex","routines","threads" but got ""

```
## Configuration

* Diun version : 4.15.1
* Platform (windows/linux) :  Linux/Synology Diskstation Manager 6.2.4-25556
* System info (type `uname -a`) : `Linux MyNAS 3.10.105 #25556 SMP Thu Mar 18 12:57:19 CST 2021 x86_64 GNU/Linux synology_braswell_916+`

> Paste your configuration files here
```
version: "3.5"

networks:
  diun:
    name: diun

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun

    labels:
      com.centurylinklabs.watchtower.enable: true
      diun.enable: true
      
    networks:
      - diun
    
    volumes:
      - "${HOST_DOCKER_DIR}/${COMPOSE_PROJECT_NAME}/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
    environment:
       TZ="Europe/Rome"
       DIUN_NOTIF_MAIL_HOST=mailhost.mydomain.com
       DIUN_NOTIF_MAIL_PORT=587
       DIUN_NOTIF_MAIL_LOCALNAME=diun.mydomain.com
       DIUN_NOTIF_MAIL_USERNAME=mailuser
       DIUN_NOTIF_MAIL_PASSWORD=mailpwd
       DIUN_NOTIF_MAIL_FROM=diun@mydomain.com
       DIUN_NOTIF_MAIL_TO=myemail@mydomain.com
       DIUN_PROVIDERS_DOCKER=true

    restart: unless-stopped
```

### Logs

```
Usage: diun

Docker image update notifier. More info: https://github.com/crazy-max/diun

diun: error: --profiler must be one of "alloc","block","cpu","heap","mem","mutex","routines","threads" but got ""
```

**Comment by crazy-max** [comment]
@buxm Thanks for your feedback. Should be fixed with latest release.

**Comment by buxm** [comment]
> @buxm Thanks for your feedback. Should be fixed with latest release.

Many thanks! Yes it works now.
