### ISSUE TITLE
Update FAQ for DockerHub limits

### ISSUE THREAD

**Issue by XPlantefeve** [crazy-max/diun#346]
Stress the importance of max_tags, include_tags, and exclude_tags in the DockerHub limits section of the FAQ.

By default, DIUN seems to downloads manifest for each and every tagged version ever released. For active/old projects, it can be hundreds of manifests, hitting the rate limits of DockerHub easily. It might be useful to add a note to that effect to the relevant section of the fact: one does not need hundreds of obolete releases information.

It might even be an idea to have a default value for max_tags on new installations? Or maybe to default to the "latest" tag? It seems to be what I'm after most of the times.

I don't known the internals of DIUN, so I'm making assumptions here. Feel free to close if I'm wrong.

**Comment by XPlantefeve** [comment]
Aaaand, it appears that I was wrong in my assumptions: DIUN is not downloading hundreds of manifests by default. It just happened because I followed the example on https://crazymax.dev/diun/providers/docker/ without understanding what watch_repo=true meant.

I'm not closing this ticket myself because I still think that a warning somewhere in the documentation could be a good idea. If only a notice in the relevant entry in the docker labels table.

**Comment by crazy-max** [comment]
@XPlantefeve 

> Aaaand, it appears that I was wrong in my assumptions: DIUN is not downloading hundreds of manifests by default. It just happened because I followed the example on https://crazymax.dev/diun/providers/docker/ without understanding what watch_repo=true meant.

Yes that's it

> I'm not closing this ticket myself because I still think that a warning somewhere in the documentation could be a good idea. If only a notice in the relevant entry in the docker labels table.

Sure I will make a note about that.
