### ISSUE TITLE
[Question adding update/recreate feature, based on label or argument

### ISSUE THREAD

**Issue by zilexa** [crazy-max/diun#349]
I considered using Pullio for notifications since it also optionally allows updating and only 6 of my 26 containers would qualify for auto-updates. But Pullio has no email notifications. Your email notification is indeed beautiful.. 

That is why I wonder and would like to ask if you would consider adding a feature to optionally (not by default ) update images if a new version is available and if a label is present in Compose/the container. 
```
labels:
      - "diun.enable=true"
      - "diun.auto-update=true"
 ```

**Comment by crazy-max** [comment]
@zilexa https://github.com/crazy-max/diun/issues/2#issuecomment-500403408
