### ISSUE TITLE
Allow use of either docker config.json or GitLab token

### ISSUE THREAD

**Issue by SimplicityGuy** [crazy-max/diun#357]
## Behaviour
There doesn't seem to be a way to use the Docker config.json file (that already contains credentials for other registries) or using the GitLab token to access private registries.

### Expected behaviour
I expect to be able to use my private GitLab registry.

**Comment by crazy-max** [comment]
@SimplicityGuy [Not yet implemented](https://github.com/crazy-max/diun/blob/1491bf0833e51c2515e8a6b661397ddb8109df2d/pkg/registry/manifest.go#L34-L39). You have to use the [registry options](https://crazymax.dev/diun/config/regopts/).
