### ISSUE TITLE
Confused about watch_repo label

### ISSUE THREAD

**Issue by airdogvan** [crazy-max/diun#365]
Not sure I understand the purpose of watch repo.  

If I use that label for something like Nextcloud (which has literally hundreds of versions) for instance every time the script runs it of course does hundreds of pulls from the repo with the consequence that on the next container the script checks I get the message "number of pulls exceeded" since docker hub now limits the number of pulls/day.

If I don't have the label watch repo will the script still detect new versions?

**Comment by crazy-max** [comment]
@airdogvan 

> If I use that label for something like Nextcloud (which has literally hundreds of versions) for instance every time the script runs it of course does hundreds of pulls from the repo with the consequence that on the next container the script checks I get the message "number of pulls exceeded" since docker hub now limits the number of pulls/day.

Indeed if the target repository contains a lot of tags it will affect your rate limit. What you can do is to allow a maximum number of tags to be scanned with the [`max_tags` label](https://crazymax.dev/diun/providers/docker/#docker-labels).

> If I don't have the label watch repo will the script still detect new versions?

If you don't use the `watch_repo` label, then you will be notified on changes for the actual tag of the image (latest if not defined).

**Comment by crazy-max** [comment]
@airdogvan 

> May I ask what is then the use of the watch repo label?

If you watch an image with an immutable tag like `alpine:3.13.5` (often semver) you will not be notified if a new tag `alpine:3.13.6` is created because you don't watch the repository.

> Very useful program by the way and thank you for making it available. Much prefer this way than watchtower's automatic updates. I like to keep control on what's being updated.

Thanks glad you like it :)
