### ISSUE TITLE
Diun on Synology DiskStation

### ISSUE THREAD

**Issue by VanKurt** [crazy-max/diun#37]
### Behaviour

When running diun on a Synology DiskStation, the following error comes up in the logs:

> ERR Cannot create Docker client error="Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39" provider=docker-local

#### Steps to reproduce this issue

1. Install docker package on DiskStation
2. Download Diun latest
3. Start Diun container

#### Expected behaviour

Diun should start normally without any errors.

#### Actual behaviour

The error mentioned above prevents diun from starting correctly.

### Configuration

* Diun version : lastest
* Platform (windows/linux) : linux (Synology NAS)

**Comment by crazy-max** [comment]
Duplicated of #29
