### ISSUE TITLE
image scanning on self-hosted docker registry using http endpoint fails

### ISSUE THREAD

**Issue by mandarons** [crazy-max/diun#376]
### Steps to reproduce this issue

1. Self-host docker registry using image: `registry:2` at e.g. http://my-server:5000/
2. Have a container created using image hosted at http://my-server:5000/ 
3. See below error in `diun` container log

WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: error pinging docker registry my-server:5000: Get \"https://my-server:5000/v2/\": http: server gave HTTP response to HTTPS client"

### Expected behaviour
No failure.

> Tell me what should happen
`diun` should allow/handle `http` registries
### Actual behaviour
`diun` should try HTTP if HTTPS fails OR allow user to set http option in config file
> Tell me what happens instead
error is thrown and images are not scanned
## Configuration
Default
* Diun version : 4.16.1
* Platform (windows/linux) : Docker
* System info (type `uname -a`) : Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 Linux

> Paste your configuration files here
> * docker-compose.yml
> * k8s deployment configuration
> * environment variables
> * diun config file
> * ...

### Logs
WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: error pinging docker registry my-server:5000: Get \"https://my-server:5000/v2/\": http: server gave HTTP response to HTTPS client"

```
# paste logs here (set log-level to debug and enable log-caller)
```

**Comment by crazy-max** [comment]
@mandarons You have to specify the [registry options](https://crazymax.dev/diun/config/regopts/). Something like this should work:

```yaml
regopts:
  - name: "my-server:5000"
    selector: image
    insecureTLS: true
```

**Comment by mandarons** [comment]
> @mandarons You have to specify the [registry options](https://crazymax.dev/diun/config/regopts/). Something like this should work:
> 
> ```yaml
> regopts:
>   - name: "my-server:5000"
>     selector: image
>     insecureTLS: true
> ```

It worked! thanks.
