### ISSUE TITLE
Kubernetes deployment should use args and not command 

### ISSUE THREAD

**Issue by paddatrapper** [crazy-max/diun#423]
### Steps to reproduce this issue

1. Deploy Kubernetes using https://crazymax.dev/diun/providers/kubernetes/#quick-start

### Expected behaviour

The pod should deploy and run successfully.

### Actual behaviour

It fails to find binary 'serve' in $PATH. This is because the Deployment spec uses

```yaml
command: ["serve"]
```

This should be:

```yaml
args: ["serve"]
```

## Configuration

* Diun version : 4.19.0
* Platform (windows/linux) : kubernetes on Linux

**Comment by crazy-max** [comment]
@paddatrapper Thanks for your feedback, feel free to open a PR.

**Comment by paddatrapper** [comment]
Sure, just not sure if the other references in #393 need to be updated too

**Comment by crazy-max** [comment]
Others are ok.
