### ISSUE TITLE
Result sorting

### ISSUE THREAD

**Issue by vl-bwalocha** [crazy-max/diun#43]
Hi,

The results from (i.e. Static) provider are alphabetically sorted.
Let say we have the following images:
```
docker:latest
docker:10.0.0
docker:9.9.0
docker:9.8.0
docker:9.7.0
...
```
and the rule:
```
- name: docker.io/xxx/docker
      watch_repo: true
      max_tags: 10
```
The result will be:
```
docker:9.9.0
docker:9.8.0
docker:9.7.0
...
```
If you are lucky at the end will be included `docker:10.0.0` (it depends on `max_tags`).
It is because the images are sorted by tag in alphabetical order. I thing, better will be to process image list by creating date.

The problem you can notice on the real example:

```
- name: docker.io/gitlab/gitlab-ce
      watch_repo: true
      max_tags: 1000
```
The results starts from `latest`, then with tag `9.*.*` instead of the newest: `12.*.*`

cheers!

**Comment by crazy-max** [comment]
Hi @vl-bwalocha,

> The results from (i.e. Static) provider are alphabetically sorted.

Actually tags are sorted as they arrive through the registry API. The underlying endpoint for Docker Hub to fetch tags for a repository is `https://index.docker.io/v2/crazymax/cloudflared/tags/list`. With this example the result is:

```json
{
  "name": "crazymax/cloudflared",
  "tags": [
    "2019.10.1",
    "2019.10.2",
    "2019.10.4",
    "2019.11.0",
    "2019.11.2",
    "2019.11.3",
    "2019.12.0",
    "2019.9.0",
    "2019.9.1",
    "2019.9.2",
    "2020.2.0",
    "latest"
  ]
}
```

Then the [order is reversed in Diun](https://github.com/crazy-max/diun/blob/bac975009afbc4aa802913ecc0c314957fa0a1d6/pkg/registry/tags.go#L56-L60) to have latest tags first but as you stipulated, the order is alphabetical through this endpoint.

What we can do here is analyze each tag to get his created date but it could be a cumbersome operation. Keep you in touch if I find something better.
In the meantime, grab all the tags :rocket:

**Comment by vl-bwalocha** [comment]
Thanks for the response and the API link.
I've checked the API v2 documentation and indeed the response is ordered lexically:
[listing-image-tags](https://docs.docker.com/registry/spec/api/#listing-image-tags)
There is no documented way to specify the sort order.
They only support limiting the result tag list (pagination).

I agree, analyzing all tag would be very bad idea. 
We should call for all tags until they publish rational API endpoint.

I really appreciate of your work @crazy-max, superior work!
Have a nice day!
