### ISSUE TITLE
Notification - Choose between new image or updated image

### ISSUE THREAD

**Issue by GeoCookie** [crazy-max/diun#438]
Hi,

Is there a way to only get notified when a new image is available and not when an image has been updated (or vice versa)?

Thank you for your work !

Cheers

**Comment by crazy-max** [comment]
@GeoCookie 

> Is there a way to only get notified when a new image is available and not when an image has been updated (or vice versa)?

No but it's a good idea

**Comment by norsemanGrey** [comment]
> Hi,
> 
> Is there a way to only get notified when a new image is available and not when an image has been updated (or vice versa)?
> 
> Thank you for your work !
> 
> Cheers

Sorry for noob question, I am probably missing something here. For a specific image what is the difference between a **new** image and and **updated** image? Would you not just have updated versions of an image?

**Comment by crazy-max** [comment]
@norsemanGrey

> Would you not just have updated versions of an image?

If you watch all tags for an image (`watch_repo` opt) then you can have a "new image" notification when a new tag is pushed.

**Comment by norsemanGrey** [comment]
> If you watch all tags for an image (`watch_repo` opt) then you can have a "new image" notification when a new tag is pushed.

Ok, I think I see. So a new image is the release of a new tag for that image while an update is an new version of an image with a specific tag?
