### ISSUE TITLE
RSS feed rather than notification

### ISSUE THREAD

**Issue by oliroe** [crazy-max/diun#443]
Hi

Would it be possible to have an RSS feed for changes rather than sending a notification?

Thanks

**Comment by crazy-max** [comment]
Can you explain more about your use case?

**Comment by oliroe** [comment]
Hi

This may be very specific to me. I use an RSS reader for keeping track of all my alerts (incl Github commits/issues/releases, changes to websites etc etc) so for me it would be great to be notified of updates to my Docker containers as an RSS feed rather than using Pushover/Telegram/Email etc. 

It may just be me who has an unusual workflow so feel free to close this if you don't think there's a wider benefit

**Comment by cwldev** [comment]
I'm the same. RSS would be very useful. Being able to check on what containers need updates while reading my daily news would be perfect. RSS and it's regular updating seems to line up perfectly for something like this.

**Comment by crazy-max** [comment]
I dunno if this functionality should be integrated into Diun. RSS feeds are not event based like other notification providers in this project. This would require creating and exposing an endpoint to be able to subscribe to the RSS feed and also keeping some kind of history of the image updates, which would increase complexity and security risks that I don't really want to address for Diun.

**Comment by cwldev** [comment]
Totally understandable. This may not be great given those reasons. Because it's useful may not make it practical. 

One of the biggest challenges I have is when I'm coming back to diun after some time has passed. Having to go over either the docker log or Discord (what I use) notifications to see what needs to be updated is sometimes a challenge I feel like I miss things. It would nice to just be able to get a list of what updates are available now - like invoking a command to check all images now? Is that possible?

**Comment by crazy-max** [comment]
@cwldev 

> like invoking a command to check all images now? Is that possible?

You can use the [inspect command](https://crazymax.dev/diun/usage/command-line/#image-inspect) for that purpose:

```console
$ docker-compose exec diun diun image inspect --image alpine
+----------+----------------------+-------------------------------------------------------------------------+
| TAG      | CREATED              | DIGEST                                                                  |
+----------+----------------------+-------------------------------------------------------------------------+
| latest   | 2021-08-06T17:19:45Z | sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae |
| 3.14.1   | 2021-08-06T17:19:45Z | sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae |
| 3.14     | 2021-08-06T17:19:45Z | sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae |
| 3        | 2021-08-06T17:19:45Z | sha256:eb3e4e175ba6d212ba1d6e04fc0782916c08e1c9d7b45892e9796141b1d379ae |
| 20210804 | 2021-08-04T21:19:39Z | sha256:2f77b6664f181b246244f9cd052155e74fb3f26d2a502edecd5fff0fc4bda388 |
| edge     | 2021-08-04T21:19:39Z | sha256:2f77b6664f181b246244f9cd052155e74fb3f26d2a502edecd5fff0fc4bda388 |
| 20210730 | 2021-07-30T17:19:39Z | sha256:12341c2503d96f13a17b0c935ae9090034e317afdfc934f1e0df1a5be813e73e |
| 3.14.0   | 2021-06-15T22:19:37Z | sha256:adab3844f497ab9171f070d4cae4114b5aec565ac772e2f2579405b78be67c96 |
| 3.10.9   | 2021-04-14T19:20:05Z | sha256:451eee8bedcb2f029756dc3e9d73bab0e7943c1ac55cff3a4861c52a0fdd3e98 |
| 3.10     | 2021-04-14T19:20:05Z | sha256:451eee8bedcb2f029756dc3e9d73bab0e7943c1ac55cff3a4861c52a0fdd3e98 |
| 3.11.11  | 2021-04-14T19:19:56Z | sha256:6cf3d8abc08cf3792d590152d7a4628ec827621f55b1d3150383f5f39335d6eb |
| 3.11     | 2021-04-14T19:19:56Z | sha256:6cf3d8abc08cf3792d590152d7a4628ec827621f55b1d3150383f5f39335d6eb |
| 3.12     | 2021-04-14T19:19:49Z | sha256:de25c7fc6c4f3a27c7f0c2dff454e4671823a34d88abd533f210848d527e0fbb |
| 3.12.7   | 2021-04-14T19:19:49Z | sha256:de25c7fc6c4f3a27c7f0c2dff454e4671823a34d88abd533f210848d527e0fbb |
| 3.13     | 2021-04-14T19:19:39Z | sha256:1d30d1ba3cb90962067e9b29491fbd56997979d54376f23f01448b5c5cd8b462 |
| 3.13.5   | 2021-04-14T19:19:39Z | sha256:1d30d1ba3cb90962067e9b29491fbd56997979d54376f23f01448b5c5cd8b462 |
| 3.10.8   | 2021-03-31T20:10:25Z | sha256:4929878917a37edf0b7f69594552508a3432fe304335dd92be29bbaa839362ed |
| 3.11.10  | 2021-03-31T20:10:19Z | sha256:bf5fa774f08a9ed2cb301e522b769d43d48124315a4ec50eae3228d03b9dc558 |
| 3.12.6   | 2021-03-31T20:10:13Z | sha256:834e9309b5ef0f78d8d20ef0652e7b0272fe97b5baf45720e1b830eaf013cc1b |
| 3.13.4   | 2021-03-31T20:10:06Z | sha256:ec14c7992a97fc11425907e908340c6c3d6ff602f5f13d899e6b7027c9b4133a |
| 3.10.7   | 2021-03-25T22:19:48Z | sha256:f2fa517acf6123318bc893c411f34570cea193367b33bd3be1d90c7fbefe72a5 |
| 3.11.9   | 2021-03-25T22:19:43Z | sha256:41bb50b86a6878cb425a850e23512e3bf84d4b26c845bf29445a7ec149e96898 |
| 3.12.5   | 2021-03-25T22:19:38Z | sha256:d1eaae2a6814b4b10a722fa75e8a6b53db42d1bf531395a107fea0458bfbf1d8 |
| 3.13.3   | 2021-03-25T22:19:32Z | sha256:826f70e0ac33e99a72cf20fb0571245a8fee52d68cb26d8bc58e53bfa65dcdfa |
| 20210212 | 2021-03-25T22:19:27Z | sha256:a81f67aca260e41b2260a4cf91ac4435dcad62ccc108ab19ae3077aafa1a4722 |
| 3.10.6   | 2021-02-24T20:20:20Z | sha256:0b4d282d7ae7cf5ed91801654a918aea45d6c1de6df0db6a29d60619141fb8de |
| 3.11.8   | 2021-02-24T20:20:12Z | sha256:23866dc6f81cc5dc69185b8a3d69f9ad303ac7fc03a4557659fb30ff72306452 |
| 3.12.4   | 2021-02-24T20:20:03Z | sha256:a295107679b0d92cb70145fc18fb53c76e79fceed7e1cf10ed763c7c102c5ebe |
| 3.13.2   | 2021-02-17T21:19:54Z | sha256:a75afd8b57e7f34e4dad8d65e2c7ba2e1975c795ce1ee22fa34f8cf46f96a3be |
| 3.13.1   | 2021-01-28T23:19:38Z | sha256:08d6ca16c60fe7490c03d10dc339d9fd8ea67c6466dea8d558526b1330a85930 |
| 3.13.0   | 2021-01-15T02:23:51Z | sha256:d9a7354e3845ea8466bb00b22224d9116b183e594527fb5b6c3d30bc01a20378 |
| 20201218 | 2020-12-18T19:33:58Z | sha256:56e8a54633573bc40a003884a01e60fb31d070d05e220d244e88ca1c4b5815fa |
...
```

**Comment by cwldev** [comment]
Yea, that's not what I meant. You're describing looking at all versions of one image.

I'm just after asking - of all running images on my server which does diun think need to be updated right now?

Might look like this:

diun -currentupdates

All Detected Images Needing Update:
alpine
wordpress
tt-rss
mysql
caddy:alpine
linuxserver/bookstack

Note: The last detected / notified update might be just one thing (mysql), but I'm after a complete list.

**Comment by crazy-max** [comment]
@cwldev

> diun -currentupdates

We could add that yes.

**Comment by cwldev** [comment]
It's something that would be really useful :) 

diun is great already, however. I wanted to just say I appreciate the work you do. Thank you.

**Comment by crazy-max** [comment]
@cwldev 

> It's something that would be really useful :)

Can you open a new issue for this feature please?

> diun is great already, however. I wanted to just say I appreciate the work you do. Thank you.

Thanks :)
