### ISSUE TITLE
Dockerfile parsing broken with buildkit v0.9.0

### ISSUE THREAD

**Issue by waiwaing** [crazy-max/diun#444]
As of [3b9a36](https://github.com/crazy-max/diun/commit/3b9a365c47abbcff672751c6b8354296b963acf0) which upgraded buildkit to 0.9.0, Dockerfile parsing is broken and the Dockerfile provider does not detect any images to analyze. This does not affect any released versions of Diun.

This is because the buildkit parser AST no longer lowercases the command name - see [buildkit 768a12](https://github.com/moby/buildkit/commit/768a12bd0dde041fcab97837b513f6f39d72dd15#diff-9538884bda9260af9062f20d3fc511fe5fd1f386e31afee56b5f2aa53b926659). As a result, Diun is now comparing an uppercase command name from the Dockerfile (e.g. `FROM`) to a lowercase command name from the Buildkit Docker command constants - see [image.go:31-33](https://github.com/crazy-max/diun/blob/master/pkg/dockerfile/image.go#L31-L33).

I may be able to raise a PR for this week, but wanted to highlight the issue to make sure a release doesn't go out with this broken as it doesn't look like there are any unit tests yet for the Dockerfile provider. (And indeed, someone else may get around to submitting a PR for this before I do!)

**Comment by crazy-max** [comment]
@waiwaing Oh thanks for testing the edge release! Feel free to open a PR sure!
