### ISSUE TITLE
diun image remove --all command appears to have no effect

### ISSUE THREAD

**Issue by adhawkins** [crazy-max/diun#478]
Looking at the source, it appears that the command doesn't make any reference to the 'all' parameter.

### Steps to reproduce this issue

1. run 'diun image remove --help' - observe '--all' option
2. run 'diun image remote --all' - error reported about missing 'image' parameter

### Expected behaviour

All images should be removed

### Actual behaviour

```
diun image remove --help
Usage: diun image remove --image=STRING

Remove an image manifest from database.

Flags:
 -h, --help            Show context-sensitive help.
      --version

      --grpc-authority="127.0.0.1:42286"
                        Link to Diun gRPC API.
      --image=STRING    Image to remove.
      --all             Remove all manifests from the database.
```

```
diun image remove --all
Usage: diun image remove --image=STRING

Remove an image manifest from database.

Run "diun image remove --help" for more information.

diun: error: missing flags: --image=STRING
```

## Configuration

* Diun version : 4.19.0
* Platform (windows/linux) : linux (docker)
* System info (type `uname -a`) : Linux 094deddb02ec 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 Linux

**Comment by crazy-max** [comment]
@adhawkins Yes this flag is not yet implemented. Was thinking of using [`prune` command](https://github.com/crazy-max/diun/blob/fe8482999c28a5df48e4cfb21eb446b4f6cbdd5b/cmd/image.go#L24) instead.

**Comment by adhawkins** [comment]
Ok, it's no big deal. I was just experimenting with a few things and spotted that command. Thought I'd post a reminder that you haven't implemented it yet. Perhaps at least remove it from the help until it actually does something?

Thanks for a very useful utility.
