### ISSUE TITLE
Add documentation how to debug app

### ISSUE THREAD

**Issue by mad73923** [crazy-max/diun#488]
Hey,
I'd like to contribute to this project but I can't get a debugger up & running.
How do you debug your code / run it from source?

Thanks

**Comment by crazy-max** [comment]
Depends on your editor/ide but I have a dev shell environment through a dedicated container with [delve](https://github.com/go-delve/delve) myself I could provide here.

**Comment by mad73923** [comment]
Alright, thanks

**Comment by mad73923** [comment]
any news on the documentation on this?
