### ISSUE TITLE
Format .Entry.Manifest.Created

### ISSUE THREAD

**Issue by Weasy666** [crazy-max/diun#489]
I am not familiar with Go, but is it possible to format template values? I want to format `.Entry.Manifest.Created` to a more easily readable format, like `Jan 02, 2006 15:04:05 UTC`, but can't find a way to do that.

I tried `{{ .Entry.Manifest.Created.Format('Jan 02, 2006 15:04:05 UTC') }}` which results in an error: `panic: template: body:1: unexpected "(" in operand`.

I also tried a few other approaches from the [go template](https://pkg.go.dev/text/template#hdr-Actions) package, but nothing worked.

**Comment by crazy-max** [comment]
@Weasy666 Try with:

```
{{ .Entry.Manifest.Created.Format "Jan 02, 2006 15:04:05 UTC" }}
```

See also the default template body with the mail notifier as an example: https://crazymax.dev/diun/notif/mail/#default-templatebody

**Comment by Weasy666** [comment]
🤦‍♂️ i could have sworn i tried that...thx and sorry for the noise 😅
