### ISSUE TITLE
[Question]Error in logs

### ISSUE THREAD

**Issue by margaale** [crazy-max/diun#49]
I'm running diun with swarm provider. My cluster has 2 nodes, one master and 1 slave. In the diun logs i see this line, 

Cannot inspect image from service 477fke4kso3larq6bmk13ahgi error="Error: No such image: linuxserver/jackett:latest@sha256:3b858d36171d4c5346f777115173e7a6a7ebf2d5ef645ea5f226d2fd9b03fce1" provider=swarm-myswarm

Could you explain to me what does it mean?

**Comment by crazy-max** [comment]
@margaale Please create a proper [bug report](https://github.com/crazy-max/diun/issues/new?template=bug_report.md) and don't create multi issues for the same problem.

**Comment by margaale** [comment]
I was just asking the meaning of the log. I wasn't saying it was a bug. Sorry for the duplicate, I don't know how it happen...

**Comment by crazy-max** [comment]
@margaale Looks like image `linuxserver/jackett:latest@sha256:3b858d36171d4c5346f777115173e7a6a7ebf2d5ef645ea5f226d2fd9b03fce1` does not exist.

**Comment by margaale** [comment]
In docker hub? Or the pulled image?

**Comment by crazy-max** [comment]
I think this is linked to your swarm stack. Please create a proper [bug report](https://github.com/crazy-max/diun/issues/new?template=bug_report.md) to help me investigate on this.
