### ISSUE TITLE
Feature Request: API webserver notification provider

### ISSUE THREAD

**Issue by moqmar** [crazy-max/diun#514]
I'd like to use Diun with more old-school monitoring tools (like CheckMK or Nagios). For that, it would be extremely nice if it could just provide a simple webserver with a JSON API endpoint that can be queried by e.g. `check_http`, like this:

If everything's up to date:
```
GET /updates.json
204 No Content
```

If there are updates:
```
GET /updates.json
200 OK

[
  { "status": "new", "provider": "docker", "image": { "name": "...", ... }, manifest: { ... } },
  ...
]
```

Is that a feature that would have a chance to be merged if I made a pull request?

**Comment by crazy-max** [comment]
@moqmar Diun doesn't really fit with your request and also exposing this kind of endpoint is not something I'm considering for now. I have not used Nagios for a while but you can use a [passive check](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/passivechecks.html) to submit results to Nagios for processing with the [Webhook](https://crazymax.dev/diun/notif/webhook/) notification for example.
