### ISSUE TITLE
error message "no image found in manifest list for architecture arm64"

### ISSUE THREAD

**Issue by logopk** [crazy-max/diun#526]
Hi Max,

could you clarify the error message
```
diun-mbp_1   | Fri, 31 Dec 2021 17:44:05 CET WRN Cannot get remote manifest error="Cannot create image closer: choosing image instance: no image found in manifest list for architecture arm64, variant \"v8\", OS linux" image=registry.fritz.box:5000/logopk/nginx:latest provider=docker
```
as this is not a file provider. (-> https://crazymax.dev/diun/faq/#no-image-found-in-manifest-list-for-architecture-variant-os)

I'm running diun on an arm64 debian (macbook pro M1 running docker in vmware) and querying amd64 and armhf (pi3).

Happy new year!

Peter

**Comment by crazy-max** [comment]
@logopk This might be linked to https://github.com/moby/moby/issues/42893 which has been fixed since  Docker 20.10. Also can you give me the output of:

```shell
$ docker buildx imagetools inspect registry.fritz.box:5000/logopk/nginx:latest
```

**Comment by logopk** [comment]
```
Name:      registry.fritz.box:5000/logopk/nginx:latest
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:48a5562c7f85ea579681c6c6f947ec225448725f7e24f41149af95004854c19e
           
Manifests: 
  Name:      registry.fritz.box:5000/logopk/nginx:latest@sha256:f78bdef477edea042f32c6a6f9f4853dbfa54273590095289495871085656c3b
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm/v7
             
  Name:      registry.fritz.box:5000/logopk/nginx:latest@sha256:01ab80b242b7c3e0c3913c4ca4ba4ac1bff40caca610c0329945fb1a138f56ea
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64
             
  Name:      registry.fritz.box:5000/logopk/nginx:latest@sha256:d5d8337c9b04cdcfd0606b5a6ae43731b5570fdd9fdbe599a7aa9d77f8ae0974
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
```

**Comment by crazy-max** [comment]
@logopk Can you create a proper [bug report](https://github.com/crazy-max/diun/issues/new?assignees=&labels=&template=bug_report.md) please? Are you using the docker provider? Would need your diun config to have a better understanding of the root cause. Also need the output of `docker info`. Thanks.

**Comment by logopk** [comment]
@crazy-max

unfortunately - well maybe also good - I had to reset my database, and now it does not happen anymore. 🤷🏼‍♂️
All images were freshly pulled.

And yes - it happened on the docker provider.
