### ISSUE TITLE
Allow for custom script instead of notifications.

### ISSUE THREAD

**Issue by harry31415** [crazy-max/diun#53]
A nice feature would be to support running a bash script or a command instead of notifications. 
```
  script:
    enable: true
    cmd: "echo 'Hello world'>myLog.out"
```
This would make it really versatile and open up a lot of possibilities!
i.e. I would like to use diun for a custom CI/CD pipeline : 
New docker images with tag release? -> run Ansible playbook

**Comment by crazy-max** [comment]
@crazy-max It's in my backlog. Thanks for your input!

**Comment by crazy-max** [comment]
@harry31415 It's in my backlog. Thanks for your input!

**Comment by crazy-max** [comment]
Notification through [script](https://github.com/crazy-max/diun/blob/master/doc/notifications.md#script) is now available.
