### ISSUE TITLE
Synology - Telegram notification not work

### ISSUE THREAD

**Issue by schmidiij** [crazy-max/diun#551]
## Behaviour
i have the same problem like him:
[Link/](https://www.synoforum.com/threads/diun-notification-not-working.6168)

the test notification work. But after a run it didn't notificat

## Configuration

`version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    network_mode: "bridge"
    container_name: diun
    volumes:
      - "/volume1/docker/diun:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Zurich"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 0 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_TELEGRAM_TOKEN=533871013:xxxxxxxxxxxxxx"
      - "DIUN_NOTIF_TELEGRAM_CHATIDS=687826xxx"
    restart: always`

![image](https://user-images.githubusercontent.com/29889802/152137288-5067f59e-8120-4960-80fc-f34d60d49cd8.png)

### Logs

```
Wed, 02 Feb 2022 11:13:27 CET INF Starting Diun version=4.21.0
Wed, 02 Feb 2022 11:13:27 CET INF Configuration loaded from 8 environment variable(s)
Wed, 02 Feb 2022 11:13:27 CET INF Cron triggered
Wed, 02 Feb 2022 11:13:27 CET INF Found 18 image(s) to analyze provider=docker
Wed, 02 Feb 2022 11:13:30 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=18 updated=0
Wed, 02 Feb 2022 11:13:30 CET INF Cron initialized with schedule 0 0 * * *
Wed, 02 Feb 2022 11:13:30 CET INF Next run in 12 hours 46 minutes (2022-02-03 00:00:00 +0100 CET)

```

**Comment by crazy-max** [comment]
@schmidiij 

```
Wed, 02 Feb 2022 11:13:30 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=18 updated=0
```

There is no changes (`added=0`, `updated=0`), that's why you don't have any notification.
