### ISSUE TITLE
Provide custom URL for inclusion in notifications

### ISSUE THREAD

**Issue by neographophobic** [crazy-max/diun#562]
I would like to be able to include an image specific custom URL that can be sent as part of a notification. 

The use case is that at the moment when I get a notification, it points me to the container registry, however this typically does not include a change log / release notes of what has changed. If I could also provide a link to the vendors public change log / release notes then it will help me to determine if I should update the container at the current time, and any breaking changes to look out for.

For example when I monitor the diun image, I would like the notification to also include a link to https://github.com/crazy-max/diun/releases.

**Comment by crazy-max** [comment]
We could add a specific label for this like `diun.hub_link`. @TheSpad also suggested the ability to use [`org.opencontainers.image.url` label](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) for this purpose. I will think about it.

**Comment by jamesking420** [comment]
On a similar note, some images (Linuxserver.io ones?) don't seem to have a hub link.  Which is disappointing. See attached image of how my notifications look when there is no hub link (no actionable second button ("see site") in second notification). There are other suitable links connected to the image that I would think could be used? 
![Screenshot_20220322-090034~2](https://user-images.githubusercontent.com/992616/159444945-4d0b8b92-a316-4a72-a181-5ddb780f7337.png)

**Comment by jamesking420** [comment]
> @jamesking420 Doesn't look like `lscr.io` has a registry UI like Docker Hub to be able to browse images? Maybe it's a redirect to Docker Hub? cc @TheSpad
> 
> Anyway we can add [a case for `lscr.io` to generate a hublink](https://github.com/crazy-max/diun/blob/dab935d9cd303af4afb667cee287934a429ed4bc/pkg/registry/image.go#L94-L135).

I don't really know (technically) what you're asking for but there is this page:

https://fleet.linuxserver.io/

**Comment by crazy-max** [comment]
> https://fleet.linuxserver.io/

Yes that's what I was looking for, thanks. Will add an entry for it.

**Comment by TheSpad** [comment]
lscr.io uses Scarf.sh to proxy the pulls. Right now it uses ghcr as the backend but that isn't guaranteed into the future. Best option would probably be to use the `org.opencontainers.image.url` label which (for lsio images at least) should always point to the github repo (and thus release notes, etc.) for a given image.

**Comment by TheSpad** [comment]
Only issue with fleet is that there are images that won't exist there publicly but are still usable by people like the baseimages, our labs (dev playground) images, etc.

**Comment by crazy-max** [comment]
> Only issue with fleet is that there are images that won't exist there publicly but are still usable by people like the baseimages, our labs (dev playground) images, etc.

Got it, thanks for your feedback

**Comment by crazy-max** [comment]
See https://github.com/crazy-max/diun/pull/646

**Comment by neographophobic** [comment]
Thank you @crazy-max for implementing this feature. I'll start adding the labels now to my containers, and look forward to this patch being rolled into the next released version.

**Comment by Nuklon** [comment]
I was just going to add a similar feature and then saw this request 🙂 I think a custom hub link is a welcome addition, but not quite the same the ability to add an additional link. Similar to the above request, I'd like to add a link to the GitHub releases page, but it's also useful to have a link to the hub itself so you can see which variants are all available (alpine, etc).

**Comment by crazy-max** [comment]
@Nuklon 

>  I'd like to add a link to the GitHub releases page

You can with `diun.hub_link=https://github.com/user/repo` for example.

**Comment by crazy-max** [comment]
Oh having both, maybe we could have a `source_url` for this. Can you open an issue if there is not one already?

**Comment by Nuklon** [comment]
Sure, done #654.
