### ISSUE TITLE
 lscr.io Not working for me

### ISSUE THREAD

**Issue by tingisinfo** [crazy-max/diun#574]
## Behaviour

 lscr.io Not working for me

### Steps to reproduce this issue

1.
2.
3.

### Expected behaviour

> Tell me what should happen

### Actual behaviour

> Tell me what happens instead

## Configuration

* Diun version : 
* Platform (windows/linux) :
* System info (type `uname -a`) : 

> Paste your configuration files here
> * docker-compose.yml
> * k8s deployment configuration
> * environment variables
> * diun config file
> * ...

### Logs

```
# paste logs here (set log-level to debug and enable log-caller)
```

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/crazy-max/diun/issues/new?assignees=&labels=&template=bug_report.md).
