### ISSUE TITLE
GET the manifest and calculate the digest 

### ISSUE THREAD

**Issue by tfprelvas** [crazy-max/diun#594]
Hi there,

A few days ago I've open the issue #591  and  from that day I've been trying to get a way to make this work.

From Red Hat Support they didn't told me anything on how to solve this but glad we have Reddit.

A member from Red Hat community gave me a proper answer and  hopefully we can workout with this ( check the post ):

https://www.reddit.com/r/redhat/comments/u1pu6c/errorcannot_get_image_digest_from_head_request/

`I'll note that the [Docker Registry API](https://docs.docker.com/registry/spec/api/#digest-header) specifies that registries may specify that Docker-Content-Digest header, but it is not required. Client tools tend to assume that all registries send that header since the most popular ones do. It would be better-compliant for those tools to GET the manifest and calculate the digest themselves (or at the very least if that header is not present). But hopefully this will be moot for you in the future once Red Hat's registries support it.`

Would be open to make some big changes for this? 

I found some identical issue on https://github.com/genuinetools/reg/issues/161 that other people worked around.

Thank you

**Comment by crazy-max** [comment]
> GET the manifest and calculate the digest themselves

There is no best-effort to fetch the manifest and calc the digest as it would impact the rate-limit on some registries like Docker Hub. Therefore this is not an option. As a side note, Red Hat seems to be the only registry that does not implement the `Docker-Content-Digest` header. So again it's up to them to implement it.
