### ISSUE TITLE
mail notifications easily marked as spam

### ISSUE THREAD

**Issue by wrosenauer** [crazy-max/diun#599]
## Behaviour
mail notifications ending up in junk folder

### Steps to reproduce this issue

1. configure mail notifications
2. wait for a notification to be sent

### Expected behaviour

Mail should not be easily marked as spam.

### Actual behaviour

My antispam solution shows the following markers:
PHISHING (3.928269) [docker.io->docker.com]
the biggest issue but somewhat expected. It's caused by the link which leads to hub.docker.com but the text above the link is docker.io. I don't see an issue with that and I need to deal with it.

MISSING_MID (2.5)
A mail should be created containing a message id. I think this could be solved in diun.

URI_COUNT_ODD (1) [9]
"Odd number of URIs in multipart/alternative message"
I'm not sure what that means honestly but probably it makes sense to someone else.

MV_CASE (0.5)
Mime-Version: 1.0 should be written as MIME-Version: 1.0

## Configuration

* Diun version : 4.21.0
* Platform (windows/linux) : Linux/k3s

**Comment by crazy-max** [comment]
Don't think we can do much about it, it's up to your mail provider and probably linked to their spam filter rules (like rspamd).
