### ISSUE TITLE
Docker: Can't access registries due to DNS issue

### ISSUE THREAD

**Issue by rpedrica** [crazy-max/diun#600]
### Steps to reproduce this issue

1. run diun with system/host DNS pointing to pi-hole running (as docker instance) on host
2. check diun logs - fails to contact registries
3. if I change my host DNS to point to an upstream DNS server instead of my pi-hole instance, then it work correctly

ie.

host dns resolv.conf = 172.16.100.11:53 (pi-hole instance) = fail
host dns resolv.conf = 8.8.8.8/1.1.1.1:53 = works/success

### Expected behaviour

> Tell me what should happen
diun docker container should be able to use DNS published on host

### Actual behaviour
diun can't use host DNS

> Tell me what happens instead
Contacting registries fails due to DNS issue.

## Configuration

* Diun version :  4.21.0
* Platform (windows/linux) : linux/docker
* System info (type `uname -a`) :  Linux googly.xstore.co.za 5.16.14 #1 SMP PREEMPT Fri Mar 11 14:42:25 CST 2022 x86_64 AMD Ryzen 5 1500X Quad-Core Processor AuthenticAMD GNU/Linux

> Paste your configuration files here
> * docker-compose.yml
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "/opt/diun/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Africa/Johannesburg"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: always

> * k8s deployment configuration
> * environment variables
> * diun config file
> * ...

### Logs

```
today at 12:56:24Wed, 27 Apr 2022 12:56:24 SAST INF Starting Diun version=4.21.0
today at 12:56:24Wed, 27 Apr 2022 12:56:24 SAST INF Configuration loaded from 5 environment variable(s)
today at 12:56:24Wed, 27 Apr 2022 12:56:24 SAST WRN No notifier available
today at 12:56:24Wed, 27 Apr 2022 12:56:24 SAST INF Cron triggered
today at 12:56:24Wed, 27 Apr 2022 12:56:24 SAST INF Found 1 image(s) to analyze provider=docker
today at 12:56:44Wed, 27 Apr 2022 12:56:44 SAST ERR Cannot list tags from registry error="pinging container registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 127.0.0.11:53: read udp 127.0.0.1:40031->127.0.0.11:53: i/o timeout" image=crazymax/diun:latest provider=docker
today at 12:56:44Wed, 27 Apr 2022 12:56:44 SAST WRN Cannot get remote manifest error="Cannot get image digest from HEAD request: pinging container registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io on 127.0.0.11:53: read udp 127.0.0.1:40031->127.0.0.11:53: i/o timeout" image=docker.io/crazymax/diun:latest provider=docker
today at 12:56:44Wed, 27 Apr 2022 12:56:44 SAST INF Jobs completed added=0 failed=1 skipped=0 unchanged=0 updated=0
today at 12:56:44Wed, 27 Apr 2022 12:56:44 SAST INF Cron initialized with schedule 0 */6 * * *
today at 12:56:44Wed, 27 Apr 2022 12:56:44 SAST INF Next run in 5 hours 3 minutes (2022-04-27 18:00:00 +0200 SAST)
```

**Comment by Macintron** [comment]
I had the exact same error. I'm also running pi-hole on the same host in a docker image where I made same DNS changes which resulted in this error. The fix was to uncomment the _name_servers_-line in _/etc/resolv.conf_ on the host: https://unix.stackexchange.com/questions/647996/docker-container-dns-not-working-with-pihole
