### ISSUE TITLE
Ignore Docker images

### ISSUE THREAD

**Issue by MrksHfmn** [crazy-max/diun#629]
Can I also ignore images so I don't get notifications? Unfortunately I could not find anything in the documentation

**Comment by crazy-max** [comment]
I guess you have the [`watchByDefault` option](https://crazymax.dev/diun/providers/docker/?h=watchby#watchbydefault) enabled. If you want to ignore a specific image, just set [`diun.enable=false` label](https://crazymax.dev/diun/providers/docker/?h=watchby#docker-labels).
