### ISSUE TITLE
Manifests and rate limits when watching new tags

### ISSUE THREAD

**Issue by caspervk** [crazy-max/diun#638]
My use case: I pin image tags in all of my compose files; e.g. `image: golang:1.18`. I would like to get notified of all _major_ and _minor_ version updates; i.e. I cannot simply watch `latest`. I am using the following configuration:
```yaml
- name: docker.io/golang
  watch_repo: true
  notify_on:
    - new
  max_tags: 2
  include_tags:
    - ^\d+\.\d+$
```
Now, the above configuration would work if Docker allowed unlimited requests to their registry, as I could simply remove the `max_tags` limit, and ingest all tags into the diun database. But the question is, why do we even need to limit ourselves in the first place? If we look at the debug logs, we see the following:
```
DBG [containers/image] GET https://auth.docker.io/token?scope=repository%3Alibrary%2Fgolang%3Apull&service=registry.docker.io
DBG [containers/image] GET https://registry-1.docker.io/v2/library/golang/tags/list
DBG 2516 tag(s) found in repository. 2 will be analyzed (2 max, 2499 not included, 0 excluded). image=docker.io/library/golang:latest
...
DBG [containers/image] GET https://registry-1.docker.io/v2/library/golang/manifests/1.8
DBG [containers/image] GET https://registry-1.docker.io/v2/library/golang/manifests/1.9
...
INF New image found image=docker.io/library/golang:1.9 provider=file
DBG Manifest saved to database image=docker.io/library/golang:1.9 provider=file
DBG Skipping notification (first check) image=docker.io/library/golang:1.9 provider=file
INF New image found image=docker.io/library/golang:1.8 provider=file
DBG Manifest saved to database image=docker.io/library/golang:1.8 provider=file
DBG Skipping notification (first check) image=docker.io/library/golang:1.8 provider=file
INF Jobs completed added=2 failed=0 skipped=1 unchanged=0 updated=0
```
I have limited myself to two tags, but diun is not analysing the latest ones - this is probably related to #518. But the question is; **why do we need to download the manifest for each image?** Diun is already retrieving `https://registry-1.docker.io/v2/library/golang/tags/list`, which contains a _full_ list of tags, here filtered to only show minor semver tags to illustrate the lexicographical ordering, which explains the previous logs analysing `1.9` and `1.8`:
```json
{
  "name": "library/golang",
  "tags": [
    "1.10",
    "1.11",
    "1.12",
    "1.13",
    "1.14",
    "1.15",
    "1.16",
    "1.17",
    "1.18",
    "1.2",
    "1.3",
    "1.4",
    "1.5",
    "1.6",
    "1.7",
    "1.8",
    "1.9"
  ]
}
```
All I want to know is when a new tag matching my regex is added to this list; I don't care about the manifest of each image, so why does diun? I am quite possibly missing something that requires diun to fetch these manifests, but from my naïve understand, it seems redundant when watching `new` tags?

Thanks so much for the continued effort into maintaining this application!

**Comment by crazy-max** [comment]
I think https://github.com/crazy-max/diun/issues/653#issuecomment-1192896240 should give you the answer about tags analysis limit.

> But the question is; why do we need to download the manifest for each image?

It downloads the manifest only if the image has not been yet analyzed by Diun or its digest is different from the one on the registry when the image has been updated.

**Comment by caspervk** [comment]
Thanks! I'll see if I can get it to work with that comment - looks promising! I'm still not sure why we need to download manifests and analyse images at all in the first place; In the case of `notify_on: new`, shouldn't simply comparing the list of image tags be enough information to calculate if a new one was added?

**Comment by caspervk** [comment]
Works brilliantly with the following config:
```yaml
- name: docker.io/golang
  watch_repo: true
  notify_on:
    - new
  max_tags: 1
  sort_tags: semver
  include_tags:
    - ^\d+\.\d+$  # minors (x.y)
```

Thanks a lot!
