### ISSUE TITLE
Odd behavior with latest

### ISSUE THREAD

**Issue by Nuklon** [crazy-max/diun#664]
### Steps to reproduce this issue

1. I have the following in custom-images.yml: 
```yml
- name: mariadb:latest
  watch_repo: true
```
2. I would expect this to only notify for :latest image. This is not the case. I've received about 40 emails yesterday of new mariadb images.
```log
Wed, 03 Aug 2022 00:01:01 CEST INF Image update found image=docker.io/library/mariadb:10.4-focal provider=file
Wed, 03 Aug 2022 00:01:02 CEST INF Image update found image=docker.io/library/mariadb:10.3.35 provider=file
Wed, 03 Aug 2022 00:01:02 CEST INF Image update found image=docker.io/library/mariadb:10.3.35-focal provider=file
Wed, 03 Aug 2022 00:01:07 CEST INF Image update found image=docker.io/library/mariadb:10.3-focal provider=file
Wed, 03 Aug 2022 00:01:07 CEST INF Image update found image=docker.io/library/mariadb:10.3 provider=file
Wed, 03 Aug 2022 00:01:07 CEST INF Image update found image=docker.io/library/mariadb:10.2.44-bionic provider=file
etc
etc
etc
```

### Expected behaviour

Only get a notification for latest.

### Actual behaviour

Receive notification for everything.

## Configuration

* Diun version : 4.22.0
* Platform (windows/linux) : Ubuntu 20.04.4 LTS

**Comment by crazy-max** [comment]
`watch_repo: true` will watch for all tags in this repo no matter which tag is referenced in name so just use:

```yaml
- name: mariadb:latest
```

**Comment by Nuklon** [comment]
Ah, that's a bit strange, but I'll remove the watch_repo then, thanks :)
