### ISSUE TITLE
Minor spelling error in 'diun notif test' CLI

### ISSUE THREAD

**Issue by Bobblybook** [crazy-max/diun#672]
* Diun version :  4.22.0 (docker image)

## Behaviour
Minor spelling correction/typo in CLI output of `diun notif test`:

![image](https://user-images.githubusercontent.com/10389944/185933475-f8bd803b-6df2-4e6c-ab0f-bd7d40927a1b.png)

Should be "notification", not "notifcation". I'm using pushover for testing this, unsure if this string is specific to pushover or shared for other services as well.
I couldn't find where in the source this string was located, or I would have made a pull req myself :(

**Comment by DougEdey** [comment]
Looks like this was fixed with https://github.com/crazy-max/diun/pull/677

**Comment by crazy-max** [comment]
Yes already fixed with #677, will be available on next release.
