### ISSUE TITLE
Record image update origin when sending notif (container, pod, ...)

### ISSUE THREAD

**Issue by Gaibhne** [crazy-max/diun#675]
I don't think this qualifies as a bug per se, so the template doesn't make much sense.

I get mails that say things like `"Docker tag [docker.io/gitlab/gitlab-runner:latest](https://hub.docker.com/r/gitlab/gitlab-runner) which you subscribed to through docker provider has been updated on docker.io registry (triggered by xxx host)"`. But that is very unhelpful! I have over 300 containers, now I have to go check them all to find which one may or may not use an outdated version of that image. Why doesn't the mail just tell me what container it found the outdated image in ?

**Comment by crazy-max** [comment]
Diun records the provider being used when sending a notification but not the origin (container, pod, filename). This is related to https://github.com/crazy-max/diun/issues/322 but with notifiers per image.

I guess that's something we could add but we need to first handle de-duplication and notifications when the same image is used by more than one container: https://github.com/crazy-max/diun/issues/342

**Comment by crazy-max** [comment]
Duplicated of https://github.com/crazy-max/diun/issues/675 actually.
