### ISSUE TITLE
[HELP] Spam from frequently updated repo/image - Stackfile environment syntax

### ISSUE THREAD

**Issue by Enissay** [crazy-max/diun#687]
Hi, I am using an image that is being [updated on a daily basis](https://hub.docker.com/r/linuxserver/jackett/tags?page=1&name=amd64-version) practically which causes a lot of spam.

Using a filter on tags wont help I think but it would be helpful to just trigger the check on that specific repo once a week or so. I wonder if that is possible or maybe you have a better idea ?

Another question given I am new to diun: the [sample config.yml you have here](https://crazymax.dev/diun/providers/file/#example) what is the correct way to pass the config as env_vars. It is cleaner for me that way to pass it in a single stackfile.
Here's my attempt:
```yaml
    environment:
      - ...
      - "DIUN_PROVIDERS_CRAZYMAX_NAME=crazymax/swarm-cronjob"
      - "DIUN_PROVIDERS_CRAZYMAX_WATCH_REPO=true"
      - "DIUN_PROVIDERS_CRAZYMAX_NOTIFY_ON=new"
      - "DIUN_PROVIDERS_CRAZYMAX_INCLUDE_TAGS=^1\.2\..*"
```

**Comment by crazy-max** [comment]
> Another question given I am new to diun: the [sample config.yml you have here](https://crazymax.dev/diun/providers/file/#example) what is the correct way to pass the config as env_vars.

See https://crazymax.dev/diun/config/#environment-variables (expand "environment variables").

> to just trigger the check on that specific repo once a week or so.

Atm watch scheduler is global. Would need some changes to handle that. Can you open a new issue with a proposal please?

___

Please do not enumerate multiple requests in the same issue next time: https://crazymax.dev/diun/reporting-issue/#writing-good-bug-reports-and-feature-requests
