### ISSUE TITLE
Notification via Gotify not working

### ISSUE THREAD

**Issue by PricelessToolkit** [crazy-max/diun#693]
I got error in logs  (unsupported protocol scheme \"\"")

## Configuration

* Diun version : latest
* Platform (windows/linux) : Linux

### docker-compose.yml
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "/home/madman/docker_conf/diun:/data"
      - "/home/madman/docker_conf/diun/diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
    labels:
      - "diun.enable=true"
      - "diun.watsh_repo=true"
    restart: always

###diun.yaml

 gotify:
    endpoint: gotify
    token: AnfASyaQF1EVIHH
    priority: 1
    timeout: 30s
    templateTitle: "{{ .Entry.Image }} released"
    templateBody: |
      Docker tag {{ .Entry.Image }} which you subscribed to through {{ .Entry.Provider }} provider has been released. 

### Logs

09/30/2022 6:00:03 PM
Fri, 30 Sep 2022 18:00:03 CEST ERR Gotify notification failed error="Post \"gotify/message?token=AnfASyaQF1EVIHH\": unsupported protocol scheme \"\"" image=lscr.io/linuxserver/duplicati:latest

Sat, 01 Oct 2022 12:00:02 CEST ERR Gotify notification failed error="Post \"gotify/message?token=AnfASyaQF1EVIHH\": unsupported protocol scheme \"\"" image=ghcr.io/benphelps/homepage:latest
```

**Comment by crazy-max** [comment]
`endpoint: gotify` is not a valid endpoint. Use either `http://` or `https://` as scheme following your environment: https://crazymax.dev/diun/notif/gotify/#configuration
