### ISSUE TITLE
Diun will only see itself

### ISSUE THREAD

**Issue by zell-mbc** [crazy-max/diun#714]
### Steps to reproduce this issue

1. docker exec -it diun diun image list
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+
| NAME                    | MANIFESTS COUNT | LATEST TAG | LATEST CREATED       | LATEST DIGEST                                                           |
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+
| docker.io/crazymax/diun |               1 | latest     | 2022-07-17T16:32:14Z | sha256:c56f0a1c686cca91569f2866404f056bfce59a310cfa421d5b555b98e0fa134e |
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+
| TOTAL                   |               1 |            |                      |                                                                         |
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+

Returns only the actual diun image.

### Expected behaviour

> I think I should expect to see all ~20 images running on this host?

### Actual behaviour

> I see only diun itself

## Configuration

docker compose logs                 
diun  | Thu, 03 Nov 2022 08:32:15 CET INF Starting Diun version=4.22.0
diun  | Thu, 03 Nov 2022 08:32:15 CET INF Configuration loaded from 4 environment variable(s)
diun  | Thu, 03 Nov 2022 08:32:15 CET WRN No notifier available
diun  | Thu, 03 Nov 2022 08:32:15 CET INF Cron triggered
diun  | Thu, 03 Nov 2022 08:32:15 CET INF Found 1 image(s) to analyze provider=docker
diun  | Thu, 03 Nov 2022 08:32:17 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=1 updated=0
diun  | Thu, 03 Nov 2022 08:32:17 CET INF Cron initialized with schedule 0 */6 * * *
diun  | Thu, 03 Nov 2022 08:32:17 CET INF Next run in 3 hours 27 minutes (2022-11-03 12:00:00 +0100 CET)

thomas at homeserver in /opt/docker/diun
$ docker exec -it diun diun image list
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+
| NAME                    | MANIFESTS COUNT | LATEST TAG | LATEST CREATED       | LATEST DIGEST                                                           |
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+
| docker.io/crazymax/diun |               1 | latest     | 2022-07-17T16:32:14Z | sha256:c56f0a1c686cca91569f2866404f056bfce59a310cfa421d5b555b98e0fa134e |
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+
| TOTAL                   |               1 |            |                      |                                                                         |
+-------------------------+-----------------+------------+----------------------+-------------------------------------------------------------------------+

thomas at homeserver in /opt/docker/diun
$ cat docker-compose.yml              
version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
        #      - "./diun.yml:/diun.yml:ro"
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
    labels:
      - "diun.enable=true"
    restart: always

- Linux homeserver.local 5.15.76-1-lts #1 SMP Sat, 29 Oct 2022 09:41:33 +0000 x86_64 GNU/Linux
- Docker version 20.10.21, build baeda1f82a

**Comment by fneiraj** [comment]
hello, I had the same problem and I think it's because you have to add the "diun.enable" tag to true to the containers so that diun detects it, or add the environment variable "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true" with this diun will detect everything by default .

**Comment by zell-mbc** [comment]
Bingo, that was it! Thanks a lot for your help.

**Comment by LordSexy** [comment]
@fneiraj Thank you from a 2-year future. It helped a lot!!!

**Comment by odin568** [comment]
@fneiraj ... and from a 4 year future 😄
