### ISSUE TITLE
Feature: Exit on error

### ISSUE THREAD

**Issue by rasmusson** [crazy-max/diun#729]
I check that all my containers are working well by checking that they are running and have not stopped.
I noticed that when Diun gets an error, like not reaching the docker API it does not exit but just retries later.

Wouldn't it be better to have duin exit on these kinds of errors?

**Comment by crazy-max** [comment]
This is not a fatal/unexpected error with diun internals and therefore should not abort the application currently running. If you need some kind of notification when an error occurs for a provider, you can use a logging driver like syslog: https://docs.docker.com/config/containers/logging/syslog/
