### ISSUE TITLE
Metrics API

### ISSUE THREAD

**Issue by AthrogatePEQ** [crazy-max/diun#752]
I don't have a bug to report.  I recently deployed kubernetes (k3s) in my home lab to replace several virtual machines running various docker containers.  Diun looked like the closest to suit my needs.  But I wanted something to poll from prometheus.  So I modeled an API end point after containrr/watchtower.

I'm wondering if you are interested in this?

**Comment by crazy-max** [comment]
Related to https://github.com/crazy-max/diun/issues/201 I guess?

**Comment by AthrogatePEQ** [comment]
Yes - I did see that issue when I started.

**Comment by crazy-max** [comment]
Ok let's continue the conversation there then, thx.
