### ISSUE TITLE
Unsupported protocol scheme

### ISSUE THREAD

**Issue by STR3IKERKRYPTON** [crazy-max/diun#761]
I'm running diun and gotify in a docker environment. I'm also using portainer. 
The gotify instance works fine. [gotify test](https://gotify.net/docs/pushmsg)

But if I try to do the [test notification](https://crazymax.dev/diun/faq/) (docker exec -it diun diun notif test) from diun I get this error:
diun: error: rpc error: code = Unknown desc = Post "aDomain/message?token=rndm-token": unsupported protocol scheme ""

![grafik](https://user-images.githubusercontent.com/87895556/211567706-753fcf8b-e965-4a49-9385-31f826f562fb.png)

What does that mean?

**Comment by crazy-max** [comment]
> `Post "aDomain/message?token=rndm-token"`

Scheme looks missing, shoudl be either `http://` or `https://`
