### ISSUE TITLE
[QUESTION] Is there a way to skip check of new update ?

### ISSUE THREAD

**Issue by antoine2tt** [crazy-max/diun#769]
Hello ! 

I think that everything is on the title ! But is there a way to just skip/don't check for update on some running conatiners ?

Thanks !

**Comment by crazy-max** [comment]
I don't know if you don't show what provider you're using but with the [Docker provider](https://crazymax.dev/diun/providers/docker/) I guess you have set [`watchByDefault: true` opt](https://crazymax.dev/diun/providers/docker/#watchbydefault) so it scans all containers. If you want to disable scan for one them you just have to set [`diun.enable=false` label](https://crazymax.dev/diun/providers/docker/#docker-labels).
