### ISSUE TITLE
[question] Metadata for latest corresponding version?

### ISSUE THREAD

**Issue by luckkmaxx** [crazy-max/diun#770]
Hi, im playing with
`DIUN_NOTIF_TELEGRAM_TEMPLATEBODY`
and I love it. But I cannot see how to include the corresponding tag for "latest" tag.
as `.Meta.Version` shows the currently installed version, it could be usefull to see what is the new version, and so decide if update the container or not depending if its a major update or not, directly from my telegram notification.

**Comment by crazy-max** [comment]
`.Meta.Version` is Diun version not the image. `.Entry.Manifest.Tag` looks to be what you need. See docs for other fields: https://crazymax.dev/diun/faq/#notification-template

**Comment by crazy-max** [comment]
You might also be interested by the new `.Entry.Metadata` field: https://github.com/crazy-max/diun/pull/749

**Comment by luckkmaxx** [comment]
Thanks, so `.Entry.Image.Tag` seems to be what I need.
Anyway, when I have set the image tag as `latest`, the `.Entry.Image.Tag` returns the `latest` tag too, instead of the real latest tagged version like `v4.24.0`
So to make the notification work as expected I have to change all my docker-compose.yaml to search for a certain version, not the latest. Then when I decide to update the container, I have to set the newest/desired tag in docker-compose.yaml, instead of just get it up to receate.
