### ISSUE TITLE
Add template fields for docker container information in notifications

### ISSUE THREAD

**Issue by rhandsch** [crazy-max/diun#798]
When getting a notification I would like to see which container needs to be updated. 
It would be even better to know what compose project is meant. E.g. container label "com.docker.compose.project".

**Comment by crazy-max** [comment]
> When getting a notification I would like to see which container needs to be updated.

You can use the [`.Entry.Metadata` field](https://crazymax.dev/diun/faq/#notification-template). See https://github.com/crazy-max/diun/pull/749

**Comment by rhandsch** [comment]
Oh, this should solve my issue. I overlooked that in the documentation. Thanks!

**Comment by lubomben** [comment]
> Oh, this should solve my issue. I overlooked that in the documentation. Thanks!

Sorry @rhandsch , can you give me an example how you used the .Entry.Metadata for this solution case? Regards!

**Comment by rhandsch** [comment]
Currently I use following as `DIUN_NOTIF_MAIL_TEMPLATEBODY`:

```
          Image {{ if .Entry.Image.HubLink }}[**{{ .Entry.Image }}**]({{ .Entry.Image.HubLink }}){{ else }}**{{ .Entry.Image }}**{{ end }}
          {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}
          at <code>{{ .Entry.Manifest.Created.Format "Jan 02, 2006 15:04:05 UTC" }}</code>.
          <p>
          Container = "{{ .Entry.Metadata.ctn_names }}"
