### ISSUE TITLE
Slack notification

### ISSUE THREAD

**Issue by seoester** [crazy-max/diun#8]
It would be great to have Slack as an alternative notification destination.

A straight-forward integration could use an Incoming Webhook. Using the Incoming Webhook API is quite simple - a single POST request is required. There are also Golang clients, e.g. [ashwanthkumar/slack-go-webhook][slack-go-webhook]. Slack's [Message Builder][message-builder] previews messages created via the API.

Slack also introduced the more flexible [Block Kit][block-kit] to layout messages.

[slack-go-webhook]: https://github.com/ashwanthkumar/slack-go-webhook
[message-builder]: https://api.slack.com/docs/messages/builder
[block-kit]: https://api.slack.com/block-kit

**Comment by seoester** [comment]
I would implement the Slack integration myself, but I am rather busy for the next few weeks... Perhaps if this is still open after, I'll have a try.

**Comment by crazy-max** [comment]
Hi @seoester,
Sure, feel free to open a PR :)

**Comment by crazy-max** [comment]
@seoester Available through v2.1.0 release

**Comment by seoester** [comment]
Looks great, thanks a lot!
