### ISSUE TITLE
配置好后获取不了镜像的任何列表信息？不知道是不是配置错误

### ISSUE THREAD

**Issue by LONER-LAU** [crazy-max/diun#812]
配置：

/volume1/docker/diun/data | /data
/var/run/docker.sock | /var/run/docker.sock

DIUN_DB_PATH | /data/diun.db
DIUN_PROVIDERS_DOCKER | true
DIUN_WATCH_SCHEDULE | 0 */6 * * *
DIUN_WATCH_WORKERS | 20
LOG_JSON | false
LOG_LEVEL | info
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PROFILER_PATH | /profiler
TZ | Asia/Shanghai
 

日志：
Fri, 10 Mar 2023 09:41:32 CST INF Starting Diun version=v4.24.0

Fri, 10 Mar 2023 09:41:32 CST INF Configuration loaded from 8 environment variable(s)

Fri, 10 Mar 2023 09:41:32 CST INF Cron triggered

Fri, 10 Mar 2023 09:41:32 CST INF Found 1 image(s) to analyze provider=docker

Fri, 10 Mar 2023 09:41:35 CST INF Jobs completed added=0 failed=0 skipped=0 unchanged=1 updated=0

Fri, 10 Mar 2023 09:41:35 CST INF Cron initialized with schedule 0 */6 * * *

Fri, 10 Mar 2023 09:41:35 CST INF Next run in 2 hours 18 minutes (2023-03-10 12:00:14.614572332 +0800 CST)

**Comment by crazy-max** [comment]
Please create a proper bug report in english. Thanks.
