### ISSUE TITLE
Why can I only get 1 image? Is it a configuration error?

### ISSUE THREAD

**Issue by LONER-LAU** [crazy-max/diun#827]
### Steps to reproduce this issue

1.
2.
3.

### Expected behaviour

> Tell me what should happen

### Actual behaviour

> Tell me what happens instead

## Configuration

* Diun version :  Diun version=v4.24.0
* Platform (windows/linux) : synology
* System info (type `uname -a`) : 

> Paste your configuration files here
Thu, 23 Mar 2023 07:11:43 CET INF Starting Diun version=v4.24.0
Thu, 23 Mar 2023 07:11:43 CET INF Configuration loaded from 11 environment variable(s)
Thu, 23 Mar 2023 07:11:43 CET INF Cron triggered
Thu, 23 Mar 2023 07:11:43 CET INF Found 1 image(s) to analyze provider=docker
Thu, 23 Mar 2023 07:11:46 CET INF Jobs completed added=0 failed=0 skipped=0 unchanged=1 updated=0
Thu, 23 Mar 2023 07:11:46 CET INF Cron initialized with schedule 0 */6 * * *
Thu, 23 Mar 2023 07:11:46 CET INF Next run in 4 hours 48 minutes (2023-03-23 12:00:11.699632727 +0100 CET)

CMD	serve
ENTRYPOINT	diun

/volume1/docker/diun/data	/data
/var/run/docker.sock	/var/run/docker.sock

DIUN_DB_PATH | /data/diun.db
DIUN_WATCH_JITTER | 30s
DIUN_WATCH_SCHEDULE | 0 */6 * * *
DIUN_WATCH_WORKERS | 20
LOG_JSON | false
LOG_LEVEL | info
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PROFILER_PATH | /profiler
TZ | Europe/Paris

**Comment by DeuX01** [comment]
add DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true to the environmental variables so it will monitor all containers
