### ISSUE TITLE
Help required: install with docker

### ISSUE THREAD

**Issue by sgiannulli** [crazy-max/diun#83]
Hello,
not clear to me how to use diun with docker, step by step; up to now I'm always stopped at diun.yml mount point considered a directory not a file.
thank you

**Comment by crazy-max** [comment]
Hi @sgiannulli, you have to create the `diun.yml` before running `docker-compose up -d`, otherwise a folder named `diun.yml` will be created instead.

**Comment by sgiannulli** [comment]
Hi,
ok, first step done but now:
`Sun, 31 May 2020 18:52:32 CEST INF Starting Diun 3.0.0


Sun, 31 May 2020 18:52:32 CEST INF Cron triggered


Sun, 31 May 2020 18:52:32 CEST ERR Cannot create Docker client error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" provider=docker


Sun, 31 May 2020 18:52:32 CEST WRN No image found


Sun, 31 May 2020 18:52:32 CEST INF Cron initialized with schedule 0 * * * *


Sun, 31 May 2020 18:52:32 CEST INF Next run in 7 minutes (2020-05-31 19:00:00 +0200 CEST)`

Thank you

**Comment by crazy-max** [comment]
@sgiannulli You have to mount `/var/run/docker.sock:/var/run/docker.sock`

**Comment by sgiannulli** [comment]
yes, right.
`Sun, 31 May 2020 19:23:27 CEST WRN No image found`
I can only think that if Diun is not running inside the same docker-compose of another container it cannot monitor it, right?

**Comment by crazy-max** [comment]
@sgiannulli 

If [`watch_by_default`](https://github.com/crazy-max/diun/blob/master/doc/providers/docker.md#provider-configuration) is disabled, therefore Diun will not scan containers not [labellized](https://github.com/crazy-max/diun/blob/master/doc/providers/docker.md#docker-labels).

> I can only think that if Diun is not running inside the same docker-compose

No Diun scans all containers of the stipulated Docker endpoint (`/var/run/docker/sock` in your case).

**Comment by sgiannulli** [comment]
now the puzzle is clear, thank you very much indeed.
The only problem still here is the gmail account not sending emails, but this is a problem with many app even when you use insecure app password, not diun related.

**Comment by crazy-max** [comment]
@sgiannulli 

> The only problem still here is the gmail account not sending emails, but this is a problem with many app even when you use insecure app password, not diun related.

Something like that should work:

```yaml
notif:
  mail:
    host: "smtp.gmail.com"
    port: 587
    ssl: true
    insecure_skip_verify: false
    username: "foo"
    password: ""
    from: "diun@example.com"
    to: "foo@gmail.com"
```
