### ISSUE TITLE
Check updates on the first run / restart

### ISSUE THREAD

**Issue by Victoare** [crazy-max/diun#833]
I saw there is the firstCheckNotif option, but it seems that setting this to true will send notifications for all the discovered images in the system and not only for the ones having an update. It this due to a docker limitation?

Also if this could be done then it would be nice to have an additional onRestartNotif flag in which would make it (re)send update notifications on container restart.

**Comment by crazy-max** [comment]
> I saw there is the firstCheckNotif option, but it seems that setting this to true will send notifications for all the discovered images in the system and not only for the ones having an update. It this due to a docker limitation?

https://github.com/crazy-max/diun/issues/541#issuecomment-1022501999

> Also if this could be done then it would be nice to have an additional onRestartNotif flag in which would make it (re)send update notifications on container restart.

Not sure what you mean, Diun already checks for notifs on startup: https://github.com/crazy-max/diun/blob/ef09003a103d2dc498e935b3d9709f0bc7cddec2/internal/app/diun.go#L106-L107

**Comment by Victoare** [comment]
By that I meant when Diun is starting then it would send out notifications for all containers where updates are available.
But reading what you linked, this won't work as I imagined.

I thought this will be good for a workaround for somehow "getting a list" of containers with outdated images.

**Comment by crazy-max** [comment]
> I thought this will be good for a workaround for somehow "getting a list" of containers with outdated images.

https://github.com/crazy-max/diun/issues/464
