### ISSUE TITLE
template body syntax

### ISSUE THREAD

**Issue by vdb86** [crazy-max/diun#838]
Hello!
I've been playing with Slack notifications and I'm running into some issues, which I'm sure are related to the syntax I'm using.
My configuration is in diun.yml
I've disabled render fields, as I want to have a smaller message.
But while defining the template body, I'm running into issues
This is what I use: templateBody: Found new {{ .Entry.Image }} image {{ .Entry.Image.Digest }}
And this is what I get:
![Screenshot 2023-04-05 091206](https://user-images.githubusercontent.com/13788152/230007708-a4998fdb-2546-4eec-886c-6a49aabd25cf.jpg)
So there's no digest shown.
I'd like to achieve this if possible:
![Screenshot 2023-04-05 091231](https://user-images.githubusercontent.com/13788152/230007934-d64a7e8a-330f-4556-b74d-e23855c111d1.jpg)

It might be worth while having a section that would explain the syntax.
We've already got the names of the fields that we can use here:
https://crazymax.dev/diun/faq/#notification-template

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/crazy-max/diun/issues/new?assignees=&labels=status%2Ftriage&projects=&template=bug.yml). Thanks.
