### ISSUE TITLE
ntfy notifications - token

### ISSUE THREAD

**Issue by yesnomaybewtf** [crazy-max/diun#842]
Please add the option to add a token for ntfy notifications.
Its needed when using a self hosted ntfy server with access control enabled.

**Comment by h4ckninja** [comment]
I came here looking for documentation on ntfy. The site https://crazymax.dev/diun/notif/slack/ doesn't show ntfy that I can find. Where are the docs for it?

**Comment by yesnomaybewtf** [comment]
Here https://github.com/crazy-max/diun/blob/master/docs/notif/ntfy.mdVon meinem iPhone gesendetAm 16.04.2023 um 18:58 schrieb h4ckNinja ***@***.***>:﻿
I came here looking for documentation on ntfy. The site https://crazymax.dev/diun/notif/slack/ doesn't show ntfy that I can find. Where are the docs for it?

**Comment by h4ckninja** [comment]
Thanks!

**Comment by yesnomaybewtf** [comment]
will try this, thxVon meinem iPhone gesendetAm 23.05.2023 um 03:01 schrieb ksurl ***@***.***>:﻿
since you can set user:pass as a script for ntfy, you can also do token in this way.
this is my config for diun:
script:
  cmd: "sh"
  args:
    - "-c"
    - "/data/ntfy.sh"

this is my ntfy.sh (based on the script from #569)
#!/bin/ash

case "$DIUN_ENTRY_STATUS" in
  new)
    DIUN_ENTRY_STATUS_TEXT="is available"
    ;;
  updated)
    DIUN_ENTRY_STATUS_TEXT="has been updated"
    ;;
  *)
    DIUN_ENTRY_STATUS_TEXT="is available"
    ;;
esac

DIUN_ENTRY_REGISTRY=$(echo $DIUN_ENTRY_IMAGE | cut -d "/" -f 1)

ntfy_url="https://ntfy.<DOMAIN>/diun"
ntfy_title="$DIUN_ENTRY_IMAGE has been updated"
ntfy_message="Docker tag $DIUN_ENTRY_IMAGE which you subscribed to through $DIUN_ENTRY_PROVIDER provider $DIUN_ENTRY_STATUS_TEXT at $DIUN_ENTRY_REGISTRY (triggered by $DIUN_HOSTNAME host)"

wget -q -O - --header "Title: $ntfy_title" --header "Authorization: Bearer <TOKEN>" --post-data "$ntfy_message" $ntfy_url

exit 0

**Comment by otaconix** [comment]
You can add a username and password/token to the ntfy URL. I have the following environment variable set on my diun container:

```env
DIUN_NOTIF_NTFY_ENDPOINT=https://username:password@hostname.example
```

To be fair, I had to go through the source for the ntfy integration, and figure out it simply uses golang's `net/http` module, which supports basic auth by passing credentials in the URL. It deserves some mentioning in diun's docs :slight_smile:

**Comment by yesnomaybewtf** [comment]
Thx!Von meinem iPhone gesendetAm 11.06.2023 um 10:12 schrieb otaconix ***@***.***>:﻿
You can add a username and password/token to the ntfy URL. I have the following environment variable set on my diun container:
***@***.***
To be fair, I had to go through the source for the ntfy integration, and figure out it simply uses golang's net/http module, which supports basic auth by passing credentials in the URL. It deserves some mentioning in diun's docs :slight_smile:

**Comment by crazy-max** [comment]
> I came here looking for documentation on ntfy. The site https://crazymax.dev/diun/notif/slack/ doesn't show ntfy that I can find. Where are the docs for it?

ntfy support [has been merged](https://github.com/crazy-max/diun/pull/787) but is not yet released, that's why documentation is not yet available on the website.

> add a token for ntfy notifications.

Opened #890 to add support for access token.
