### ISSUE TITLE
Is it possible to get just the number of updates?

### ISSUE THREAD

**Issue by tushev** [crazy-max/diun#850]
Hello Max,

Is it possible to get just the number of available image updates?

It could be either a command, like `docker-compose exec diun diun updates count`, or a file with the number, that I will be able to export as bind mount outside the container.

Something like (for Ubuntu):
```
apt-get -q -y --ignore-hold --allow-change-held-packages --allow-unauthenticated -s dist-upgrade | /bin/grep  ^Inst | wc -l
```

Thanks!

**Comment by crazy-max** [comment]
> Is it possible to get just the number of available image updates?

See https://github.com/crazy-max/diun/issues/114
