### ISSUE TITLE
How does diun check for image update?

### ISSUE THREAD

**Issue by sgiannulli** [crazy-max/diun#86]
Hello,
sorry for maybe a stupid question but I'm wondering if everything works as expected; example:
I have a letsencrypt container, this is the latest image on docker hub: https://hub.docker.com/layers/linuxserver/letsencrypt/latest/images/sha256-84a8b62f135a4a810ab15286b1a30b1ec6cc8bd92c32edd0a0f1e325231be117?context=explore that has been cretaed yesterday `Digest:sha256:84a8b62f135a4a810ab15286b1a30b1ec6cc8bd92c32edd0a0f1e325231be117`
Portainer on my host reports the image to be: `sha256:a10de094dd3172fb8b531ce1f5e855a54403c1a8d9909c25217b39fee2cca270 ` created on 2020/05/30 so I would expect diun send an email alert telling a new image has been released but nothing happens

**Comment by crazy-max** [comment]
Hi @sgiannulli, can't help you without logs, configuration, etc..

**Comment by sgiannulli** [comment]
Hi,
I have attached my last log lines and diun.yml
Thank you
[diun log.txt](https://github.com/crazy-max/diun/files/4719085/diun.log.txt)
[diun.txt](https://github.com/crazy-max/diun/files/4719095/diun.txt)

**Comment by crazy-max** [comment]
@sgiannulli As stipulated by your configuration, you have enabled the Docker provider and watch image for all containers. No changes have been found for `linuxserver/letsencrypt:latest` because the manifest matches the one in Diun database. Your schedule is every hour (`0 * * * *`) so a change should have occurred between `6/1/2020 at 7:15 pm` (latest tag update on DockerHub) and `Tue, 02 Jun 2020 20:27:44 CEST`. Check your full logs to find out.

**Comment by sgiannulli** [comment]
well, I restarted everything from scratch (database cancelled, container and image too) just changing `first_check_notif: true` instead of false to avoid misunderstanding about the first nine emails but nothing changed; so maybe the problem is that I do not understand how the database is populated. Consider that the linuserver/letsencrypt image has been update twice in the last couple of hours. I have attached again the log
[log.txt](https://github.com/crazy-max/diun/files/4719811/log.txt)

**Comment by crazy-max** [comment]
@sgiannulli Thanks for your feedback can you post your diun and letsencrypt compose files here please?

**Comment by sgiannulli** [comment]
`version: '2'
services:
  diun:
    container_name: diun
    image: crazymax/diun
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
      - LOG_LEVEL=debug
      - LOG_JSON=false
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/dev-disk-by-label-orangepi2/config/diun/data:/data
      - /srv/dev-disk-by-label-orangepi2/config/diun/diun.yml:/diun.yml:ro
    restart: unless-stopped`

`letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Rome
      - URL=xxx.duckdns.org
      - EMAIL=abc@xyz.it
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=token
    volumes:
      - /srv/dev-disk-by-label-orangepi2/config/letsencrypt:/config
    ports:
      - 444:443
      - 81:80
    restart: unless-stopped`

**Comment by sgiannulli** [comment]
leave it, my stupid fault: while I corrected the PUID & PGID in my repo with 1000 value for both in portainer stack they were still 1000 and 100 as the hard drive samba owner. Now everything works, I just received an email telling the letsencrypt image has been updated on docker hub.
Sorry and thanks again for your prompt support.

**Comment by crazy-max** [comment]
@sgiannulli You're welcome, glad you solved your issue.
