### ISSUE TITLE
Reasoning for only one docker provider

### ISSUE THREAD

**Issue by logopk** [crazy-max/diun#87]
Could you please explain why I can only query one docker host with 3.0.0?

I used to query different hosts with different apps/images...

Thank You.

**Comment by crazy-max** [comment]
@logopk This is an underlying problem with the Docker API when stacking multiple clients. As an alternative you can create a Diun stack for each Docker environment or wait for #82 which will allow you to use the environment variables to mutualize this more easily.
Btw, how many Docker environments have you set up?

**Comment by logopk** [comment]
Understood, but why did it work in Version 2.x? I'm sticking with that. I may need some time to setup a multi stack environment.

**Comment by crazy-max** [comment]
@logopk This issue occurs since Docker client v19.03.10. Diun 2.6.1 uses v19.03.8. So I preferred to remove this on version 3.0.0 and leave the choice to the user to create several Diun stacks.
