### ISSUE TITLE
Configuration keeps changing

### ISSUE THREAD

**Issue by kkazakov** [crazy-max/diun#89]
I'm using docker instance to monitor, and (several times already) diun stops working after updating it. Unfortunately the configuration changed yet again. 

Is there a plan to finalize it? at least in a way that this will not break it? Like versioning or something? And then supporting different versions.

It's really annoying that way ...

**Comment by crazy-max** [comment]
@kkazakov Please create a proper [bug report](https://github.com/crazy-max/diun/issues/new?template=bug_report.md).
