### ISSUE TITLE
Discord Notification formatting got messed up (Edge)

### ISSUE THREAD

**Issue by rg9400** [crazy-max/diun#970]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/diun/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Formatting for Discord notification messages (not the embed) got disturbed in one of the recent Edge releases. The first image is the last properly formatted notification, so it's where the bug was introduced.

Before:
![image](https://github.com/crazy-max/diun/assets/39887349/7a612ea9-8b19-483a-b560-2d322818edee)

After:
![image](https://github.com/crazy-max/diun/assets/39887349/c72bec6b-0c41-4059-a852-0c4d6f479e94)

### Expected behaviour

Formatting should not be disturbed, so it should look like the first image

### Actual behaviour

It looks like the second image

### Steps to reproduce

1. Update Diun to latest Edge
2. Set up Discord notification webhooks
3. Have a new image be updated
4. Verify formatting of Discord notification

### Diun version

v4.25.0-71-gc78d877

### Docker info

```text
I do not believe this is relevant, but I can provide if so
```

### Docker Compose config

```yaml
Not relevant
```

### Logs

```text
Not relevant (can provide if deemed relevant, but I think this is just a notification formatting error)
```

**Comment by crazy-max** [comment]
Thanks for your report!

Ok so `v4.25.0-79-g54a61c4` is the actual version where it seems broken. That's odd though, I can't find the commit id `g54a61c4` in the working tree.

But anyway, I think this could be linked to https://github.com/crazy-max/diun/pull/927. Can you try with latest edge to see if you still repro by any chance?

**Comment by crazy-max** [comment]
Thanks I'm taking a look

**Comment by crazy-max** [comment]
@rg9400 If you want to pull `edge` again, this should be fixed.

**Comment by rg9400** [comment]
@crazy-max can confirm, it is fixed now. Thanks!

**Comment by crazy-max** [comment]
And thank you for testing edge releases
